"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AlabamaRegistrationType(str, Enum):
    SELLERS_USE_LOCAL = "SELLERS_USE_LOCAL"
    SIMPLIFIED_SELLERS_USE_TAX = "SIMPLIFIED_SELLERS_USE_TAX"
    SALES_TAX = "SALES_TAX"
