"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alabamaregistrationtype import AlabamaRegistrationType
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AlabamaFieldsTypedDict(TypedDict):
    r"""State-specific fields for Alabama registration import.

    Values are plaintext in API request/response models. Before persistence,
    ``access_code`` and ``third_party_password`` are encrypted with
    ``kintsugi_encrypt`` (see ``finalize_jurisdiction_specific_fields_for_storage``).
    """

    registration_type: AlabamaRegistrationType
    business_name: str
    r"""Business name as registered with the state of Alabama."""
    sign_on_id: str
    r"""Alabama Sign On ID used to access My Alabama Taxes (MAT)."""
    access_code: str
    r"""Alabama Access Code used to access My Alabama Taxes (MAT)."""
    third_party_password: str
    r"""Third-party password for Kintsugi access to My Alabama Taxes (MAT)."""
    sales_tax_id: str
    r"""Alabama state-issued sales tax account number (Department of Revenue)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup in their Alabama tax account."""
    local_tax_id: NotRequired[Nullable[str]]
    r"""Local tax account or permit ID used for Alabama local sales tax (e.g. county or municipal)."""


class AlabamaFields(BaseModel):
    r"""State-specific fields for Alabama registration import.

    Values are plaintext in API request/response models. Before persistence,
    ``access_code`` and ``third_party_password`` are encrypted with
    ``kintsugi_encrypt`` (see ``finalize_jurisdiction_specific_fields_for_storage``).
    """

    registration_type: AlabamaRegistrationType

    business_name: str
    r"""Business name as registered with the state of Alabama."""

    sign_on_id: str
    r"""Alabama Sign On ID used to access My Alabama Taxes (MAT)."""

    access_code: str
    r"""Alabama Access Code used to access My Alabama Taxes (MAT)."""

    third_party_password: str
    r"""Third-party password for Kintsugi access to My Alabama Taxes (MAT)."""

    sales_tax_id: str
    r"""Alabama state-issued sales tax account number (Department of Revenue)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup in their Alabama tax account."""

    local_tax_id: OptionalNullable[str] = UNSET
    r"""Local tax account or permit ID used for Alabama local sales tax (e.g. county or municipal)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed", "local_tax_id"])
        nullable_fields = set(["local_tax_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
