"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .arkansasregistrationtype import ArkansasRegistrationType
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ArkansasFieldsTypedDict(TypedDict):
    r"""State-specific fields for Arkansas registration import (ATAP).

    Plaintext in API request/response; persisted as JSON on the registration.
    """

    registration_type: ArkansasRegistrationType
    business_name: str
    r"""Business name as registered with the state of Arkansas."""
    ar_account_id: str
    r"""Arkansas Taxpayer Access Point (ATAP) account ID."""
    zip_code: str
    r"""ZIP code associated with the Arkansas registration."""
    last_payment_to_state: str
    r"""Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not include $ or commas)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup in their Arkansas tax account."""


class ArkansasFields(BaseModel):
    r"""State-specific fields for Arkansas registration import (ATAP).

    Plaintext in API request/response; persisted as JSON on the registration.
    """

    registration_type: ArkansasRegistrationType

    business_name: str
    r"""Business name as registered with the state of Arkansas."""

    ar_account_id: str
    r"""Arkansas Taxpayer Access Point (ATAP) account ID."""

    zip_code: str
    r"""ZIP code associated with the Arkansas registration."""

    last_payment_to_state: str
    r"""Last payment made to the state as a plain decimal (e.g. 0.00 if no payment has been made; do not include $ or commas)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup in their Arkansas tax account."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
