"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attachmentread import AttachmentRead, AttachmentReadTypedDict
from .countrycodeenum import CountryCodeEnum
from .customerread import CustomerRead, CustomerReadTypedDict
from .exemptionstatus import ExemptionStatus
from .exemptiontype import ExemptionType
from datetime import date
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BackendSrcExemptionsSerializersExemptionReadTypedDict(TypedDict):
    start_date: date
    r"""Start date for the exemption validity period (YYYY-MM-DD format)"""
    id: str
    r"""Unique identifier for the exemption"""
    exemption_type: ExemptionType
    status: ExemptionStatus
    country_code: NotRequired[CountryCodeEnum]
    jurisdiction: NotRequired[str]
    r"""The jurisdiction identifier for the exemption"""
    end_date: NotRequired[str]
    r"""End date for the exemption validity period (YYYY-MM-DD format)"""
    transaction_id: NotRequired[str]
    r"""Unique identifier for the transaction, if applicable"""
    reseller: NotRequired[bool]
    r"""Indicates whether the exemption is for a reseller"""
    fein: NotRequired[str]
    r"""Federal Employer Identification Number"""
    sales_tax_id: NotRequired[str]
    r"""Sales tax ID for the exemption"""
    customer: NotRequired[CustomerReadTypedDict]
    attachment: NotRequired[List[AttachmentReadTypedDict]]
    r"""List of attachments related to the exemption"""


class BackendSrcExemptionsSerializersExemptionRead(BaseModel):
    start_date: date
    r"""Start date for the exemption validity period (YYYY-MM-DD format)"""

    id: str
    r"""Unique identifier for the exemption"""

    exemption_type: ExemptionType

    status: ExemptionStatus

    country_code: Optional[CountryCodeEnum] = None

    jurisdiction: Optional[str] = None
    r"""The jurisdiction identifier for the exemption"""

    end_date: Optional[str] = None
    r"""End date for the exemption validity period (YYYY-MM-DD format)"""

    transaction_id: Optional[str] = None
    r"""Unique identifier for the transaction, if applicable"""

    reseller: Optional[bool] = False
    r"""Indicates whether the exemption is for a reseller"""

    fein: Annotated[Optional[str], pydantic.Field(alias="FEIN")] = None
    r"""Federal Employer Identification Number"""

    sales_tax_id: Optional[str] = None
    r"""Sales tax ID for the exemption"""

    customer: Optional[CustomerRead] = None

    attachment: Optional[List[AttachmentRead]] = None
    r"""List of attachments related to the exemption"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "country_code",
                "jurisdiction",
                "end_date",
                "transaction_id",
                "reseller",
                "FEIN",
                "sales_tax_id",
                "customer",
                "attachment",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    BackendSrcExemptionsSerializersExemptionRead.model_rebuild()
except NameError:
    pass
