"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import FieldMetadata
from typing_extensions import Annotated, TypedDict


class BodyUploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPostTypedDict(
    TypedDict
):
    file: str


class BodyUploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPost(
    BaseModel
):
    file: Annotated[str, FieldMetadata(multipart=True)]
