"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .californiaregistrationtype import CaliforniaRegistrationType
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CaliforniaFieldsTypedDict(TypedDict):
    r"""State-specific fields for California CDTFA portal registration import."""

    registration_type: CaliforniaRegistrationType
    business_name: str
    r"""Business name as registered with CDTFA."""
    sales_tax_id: str
    r"""California Sales and Use Tax ID (seller's permit / CDTFA account number)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup in their California CDTFA account."""
    cdtfa_third_party_access_security_code: NotRequired[Nullable[str]]
    r"""Optional at import; customers add this in registration credentials after CDTFA issues it. Third-party access security code from CDTFA Online Services so Kintsugi can file on your behalf."""


class CaliforniaFields(BaseModel):
    r"""State-specific fields for California CDTFA portal registration import."""

    registration_type: CaliforniaRegistrationType

    business_name: str
    r"""Business name as registered with CDTFA."""

    sales_tax_id: str
    r"""California Sales and Use Tax ID (seller's permit / CDTFA account number)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup in their California CDTFA account."""

    cdtfa_third_party_access_security_code: OptionalNullable[str] = UNSET
    r"""Optional at import; customers add this in registration credentials after CDTFA issues it. Third-party access security code from CDTFA Online Services so Kintsugi can file on your behalf."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["mfa_completed", "cdtfa_third_party_access_security_code"]
        )
        nullable_fields = set(["cdtfa_third_party_access_security_code"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
