"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class CaliforniaRegistrationType(str, Enum):
    REMOTE_SELLER = "REMOTE_SELLER"
    SALES_TAX = "SALES_TAX"
