"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alabamaregistrationpayload import (
    AlabamaRegistrationPayload,
    AlabamaRegistrationPayloadTypedDict,
)
from .arizonaregistrationpayload import (
    ArizonaRegistrationPayload,
    ArizonaRegistrationPayloadTypedDict,
)
from .arkansasregistrationpayload import (
    ArkansasRegistrationPayload,
    ArkansasRegistrationPayloadTypedDict,
)
from .californiaregistrationpayload import (
    CaliforniaRegistrationPayload,
    CaliforniaRegistrationPayloadTypedDict,
)
from .coloradoregistrationpayload import (
    ColoradoRegistrationPayload,
    ColoradoRegistrationPayloadTypedDict,
)
from .connecticutregistrationpayload import (
    ConnecticutRegistrationPayload,
    ConnecticutRegistrationPayloadTypedDict,
)
from .districtofcolumbiaregistrationpayload import (
    DistrictOfColumbiaRegistrationPayload,
    DistrictOfColumbiaRegistrationPayloadTypedDict,
)
from .floridaregistrationpayload import (
    FloridaRegistrationPayload,
    FloridaRegistrationPayloadTypedDict,
)
from .georgiaregistrationpayload import (
    GeorgiaRegistrationPayload,
    GeorgiaRegistrationPayloadTypedDict,
)
from .hawaiiregistrationpayload import (
    HawaiiRegistrationPayload,
    HawaiiRegistrationPayloadTypedDict,
)
from .idahoregistrationpayload import (
    IdahoRegistrationPayload,
    IdahoRegistrationPayloadTypedDict,
)
from .illinoisregistrationpayload import (
    IllinoisRegistrationPayload,
    IllinoisRegistrationPayloadTypedDict,
)
from .indianaregistrationpayload import (
    IndianaRegistrationPayload,
    IndianaRegistrationPayloadTypedDict,
)
from .iowaregistrationpayload import (
    IowaRegistrationPayload,
    IowaRegistrationPayloadTypedDict,
)
from .kansasregistrationpayload import (
    KansasRegistrationPayload,
    KansasRegistrationPayloadTypedDict,
)
from .kentuckyregistrationpayload import (
    KentuckyRegistrationPayload,
    KentuckyRegistrationPayloadTypedDict,
)
from .louisianaregistrationpayload import (
    LouisianaRegistrationPayload,
    LouisianaRegistrationPayloadTypedDict,
)
from .maineregistrationpayload import (
    MaineRegistrationPayload,
    MaineRegistrationPayloadTypedDict,
)
from .marylandregistrationpayload import (
    MarylandRegistrationPayload,
    MarylandRegistrationPayloadTypedDict,
)
from .massachusettsregistrationpayload import (
    MassachusettsRegistrationPayload,
    MassachusettsRegistrationPayloadTypedDict,
)
from .michiganregistrationpayload import (
    MichiganRegistrationPayload,
    MichiganRegistrationPayloadTypedDict,
)
from .minnesotaregistrationpayload import (
    MinnesotaRegistrationPayload,
    MinnesotaRegistrationPayloadTypedDict,
)
from .mississippiregistrationpayload import (
    MississippiRegistrationPayload,
    MississippiRegistrationPayloadTypedDict,
)
from .missouriregistrationpayload import (
    MissouriRegistrationPayload,
    MissouriRegistrationPayloadTypedDict,
)
from .nebraskaregistrationpayload import (
    NebraskaRegistrationPayload,
    NebraskaRegistrationPayloadTypedDict,
)
from .nevadaregistrationpayload import (
    NevadaRegistrationPayload,
    NevadaRegistrationPayloadTypedDict,
)
from .newjerseyregistrationpayload import (
    NewJerseyRegistrationPayload,
    NewJerseyRegistrationPayloadTypedDict,
)
from .newmexicoregistrationpayload import (
    NewMexicoRegistrationPayload,
    NewMexicoRegistrationPayloadTypedDict,
)
from .newyorkregistrationpayload import (
    NewYorkRegistrationPayload,
    NewYorkRegistrationPayloadTypedDict,
)
from .northcarolinaregistrationpayload import (
    NorthCarolinaRegistrationPayload,
    NorthCarolinaRegistrationPayloadTypedDict,
)
from .northdakotaregistrationpayload import (
    NorthDakotaRegistrationPayload,
    NorthDakotaRegistrationPayloadTypedDict,
)
from .ohioregistrationpayload import (
    OhioRegistrationPayload,
    OhioRegistrationPayloadTypedDict,
)
from .oklahomaregistrationpayload import (
    OklahomaRegistrationPayload,
    OklahomaRegistrationPayloadTypedDict,
)
from .ossregistrationcreatepayload import (
    OSSRegistrationCreatePayload,
    OSSRegistrationCreatePayloadTypedDict,
)
from .pennsylvaniaregistrationpayload import (
    PennsylvaniaRegistrationPayload,
    PennsylvaniaRegistrationPayloadTypedDict,
)
from .registrationcreatepayload import (
    RegistrationCreatePayload,
    RegistrationCreatePayloadTypedDict,
)
from .rhodeislandregistrationpayload import (
    RhodeIslandRegistrationPayload,
    RhodeIslandRegistrationPayloadTypedDict,
)
from .southcarolinaregistrationpayload import (
    SouthCarolinaRegistrationPayload,
    SouthCarolinaRegistrationPayloadTypedDict,
)
from .southdakotaregistrationpayload import (
    SouthDakotaRegistrationPayload,
    SouthDakotaRegistrationPayloadTypedDict,
)
from .sstregistrationcreatepayload import (
    SSTRegistrationCreatePayload,
    SSTRegistrationCreatePayloadTypedDict,
)
from .tennesseeregistrationpayload import (
    TennesseeRegistrationPayload,
    TennesseeRegistrationPayloadTypedDict,
)
from .texasregistrationpayload import (
    TexasRegistrationPayload,
    TexasRegistrationPayloadTypedDict,
)
from .utahregistrationpayload import (
    UtahRegistrationPayload,
    UtahRegistrationPayloadTypedDict,
)
from .vermontregistrationpayload import (
    VermontRegistrationPayload,
    VermontRegistrationPayloadTypedDict,
)
from .virginiaregistrationpayload import (
    VirginiaRegistrationPayload,
    VirginiaRegistrationPayloadTypedDict,
)
from .washingtonregistrationpayload import (
    WashingtonRegistrationPayload,
    WashingtonRegistrationPayloadTypedDict,
)
from .westvirginiaregistrationpayload import (
    WestVirginiaRegistrationPayload,
    WestVirginiaRegistrationPayloadTypedDict,
)
from .wisconsinregistrationpayload import (
    WisconsinRegistrationPayload,
    WisconsinRegistrationPayloadTypedDict,
)
from .wyomingregistrationpayload import (
    WyomingRegistrationPayload,
    WyomingRegistrationPayloadTypedDict,
)
from kintsugi_tax_platform_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict


CreateRegistrationTypedDict = TypeAliasType(
    "CreateRegistrationTypedDict",
    Union[
        SSTRegistrationCreatePayloadTypedDict,
        OSSRegistrationCreatePayloadTypedDict,
        WestVirginiaRegistrationPayloadTypedDict,
        MassachusettsRegistrationPayloadTypedDict,
        ConnecticutRegistrationPayloadTypedDict,
        NorthCarolinaRegistrationPayloadTypedDict,
        DistrictOfColumbiaRegistrationPayloadTypedDict,
        GeorgiaRegistrationPayloadTypedDict,
        HawaiiRegistrationPayloadTypedDict,
        IdahoRegistrationPayloadTypedDict,
        IllinoisRegistrationPayloadTypedDict,
        IndianaRegistrationPayloadTypedDict,
        IowaRegistrationPayloadTypedDict,
        KansasRegistrationPayloadTypedDict,
        WisconsinRegistrationPayloadTypedDict,
        MississippiRegistrationPayloadTypedDict,
        MichiganRegistrationPayloadTypedDict,
        MissouriRegistrationPayloadTypedDict,
        TennesseeRegistrationPayloadTypedDict,
        TexasRegistrationPayloadTypedDict,
        FloridaRegistrationPayloadTypedDict,
        VermontRegistrationPayloadTypedDict,
        VirginiaRegistrationPayloadTypedDict,
        WashingtonRegistrationPayloadTypedDict,
        CaliforniaRegistrationPayloadTypedDict,
        AlabamaRegistrationPayloadTypedDict,
        SouthDakotaRegistrationPayloadTypedDict,
        MinnesotaRegistrationPayloadTypedDict,
        RegistrationCreatePayloadTypedDict,
        ArkansasRegistrationPayloadTypedDict,
        RhodeIslandRegistrationPayloadTypedDict,
        KentuckyRegistrationPayloadTypedDict,
        MarylandRegistrationPayloadTypedDict,
        MaineRegistrationPayloadTypedDict,
        NevadaRegistrationPayloadTypedDict,
        NewJerseyRegistrationPayloadTypedDict,
        NewMexicoRegistrationPayloadTypedDict,
        NewYorkRegistrationPayloadTypedDict,
        NorthDakotaRegistrationPayloadTypedDict,
        SouthCarolinaRegistrationPayloadTypedDict,
        OklahomaRegistrationPayloadTypedDict,
        LouisianaRegistrationPayloadTypedDict,
        OhioRegistrationPayloadTypedDict,
        PennsylvaniaRegistrationPayloadTypedDict,
        ArizonaRegistrationPayloadTypedDict,
        NebraskaRegistrationPayloadTypedDict,
        UtahRegistrationPayloadTypedDict,
        ColoradoRegistrationPayloadTypedDict,
        WyomingRegistrationPayloadTypedDict,
    ],
)


CreateRegistration = TypeAliasType(
    "CreateRegistration",
    Union[
        SSTRegistrationCreatePayload,
        OSSRegistrationCreatePayload,
        WestVirginiaRegistrationPayload,
        MassachusettsRegistrationPayload,
        ConnecticutRegistrationPayload,
        NorthCarolinaRegistrationPayload,
        DistrictOfColumbiaRegistrationPayload,
        GeorgiaRegistrationPayload,
        HawaiiRegistrationPayload,
        IdahoRegistrationPayload,
        IllinoisRegistrationPayload,
        IndianaRegistrationPayload,
        IowaRegistrationPayload,
        KansasRegistrationPayload,
        WisconsinRegistrationPayload,
        MississippiRegistrationPayload,
        MichiganRegistrationPayload,
        MissouriRegistrationPayload,
        TennesseeRegistrationPayload,
        TexasRegistrationPayload,
        FloridaRegistrationPayload,
        VermontRegistrationPayload,
        VirginiaRegistrationPayload,
        WashingtonRegistrationPayload,
        CaliforniaRegistrationPayload,
        AlabamaRegistrationPayload,
        SouthDakotaRegistrationPayload,
        MinnesotaRegistrationPayload,
        RegistrationCreatePayload,
        ArkansasRegistrationPayload,
        RhodeIslandRegistrationPayload,
        KentuckyRegistrationPayload,
        MarylandRegistrationPayload,
        MaineRegistrationPayload,
        NevadaRegistrationPayload,
        NewJerseyRegistrationPayload,
        NewMexicoRegistrationPayload,
        NewYorkRegistrationPayload,
        NorthDakotaRegistrationPayload,
        SouthCarolinaRegistrationPayload,
        OklahomaRegistrationPayload,
        LouisianaRegistrationPayload,
        OhioRegistrationPayload,
        PennsylvaniaRegistrationPayload,
        ArizonaRegistrationPayload,
        NebraskaRegistrationPayload,
        UtahRegistrationPayload,
        ColoradoRegistrationPayload,
        WyomingRegistrationPayload,
    ],
)


class CreateRegistrationV1RegistrationsPostRequestTypedDict(TypedDict):
    x_organization_id: Nullable[str]
    request_body: CreateRegistrationTypedDict


class CreateRegistrationV1RegistrationsPostRequest(BaseModel):
    x_organization_id: Annotated[
        Nullable[str],
        pydantic.Field(alias="x-organization-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]

    request_body: Annotated[
        CreateRegistration,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
