"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deregisterregistrationrequest import (
    DeregisterRegistrationRequest,
    DeregisterRegistrationRequestTypedDict,
)
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class DeregisterRegistrationV1RegistrationsRegistrationIDDeregisterPostRequestTypedDict(
    TypedDict
):
    registration_id: str
    r"""The unique identifier of the registration to deregister."""
    x_organization_id: Nullable[str]
    r"""The unique identifier for the organization making the request"""
    deregister_registration_request: NotRequired[
        Nullable[DeregisterRegistrationRequestTypedDict]
    ]


class DeregisterRegistrationV1RegistrationsRegistrationIDDeregisterPostRequest(
    BaseModel
):
    registration_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the registration to deregister."""

    x_organization_id: Annotated[
        Nullable[str],
        pydantic.Field(alias="x-organization-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier for the organization making the request"""

    deregister_registration_request: Annotated[
        OptionalNullable[DeregisterRegistrationRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["DeregisterRegistrationRequest"])
        nullable_fields = set(["x-organization-id", "DeregisterRegistrationRequest"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
