"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appliedto import AppliedTo
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class DiscountBuilderTypedDict(TypedDict):
    applied_to: AppliedTo
    external_id: NotRequired[str]
    discount_amount: NotRequired[float]


class DiscountBuilder(BaseModel):
    applied_to: AppliedTo

    external_id: Optional[str] = None

    discount_amount: Optional[float] = 0

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["external_id", "discount_amount"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
