"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DocumentTypeEnum(str, Enum):
    INVOICE = "INVOICE"
    SALES_ORDER = "SALES_ORDER"
    CASH_SALE = "CASH_SALE"
    CASH_REFUND = "CASH_REFUND"
