"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ExemptionSourceEnum(str, Enum):
    r"""Source of exemption, needs extension for new sources which supports
    multi-state exemptions
    """

    NETSUITE = "NETSUITE"
    QUICKBOOKS = "QUICKBOOKS"
    INTUIT_ENTERPRISE_SUITE = "INTUIT_ENTERPRISE_SUITE"
    SAGE_INTACCT = "SAGE_INTACCT"
    SHOPIFY = "SHOPIFY"
    XERO = "XERO"
    STRIPE = "STRIPE"
    BIGCOMMERCE = "BIGCOMMERCE"
    MAGENTO = "MAGENTO"
    MAXIO = "MAXIO"
    CHARGEBEE = "CHARGEBEE"
    ZUORA = "ZUORA"
    MICROSOFT_DYNAMICS_365 = "MICROSOFT_DYNAMICS_365"
    DUALENTRY = "DUALENTRY"
    RECURLY = "RECURLY"
    SHOPLINE = "SHOPLINE"
    ORB = "ORB"
    ZENSKAR = "ZENSKAR"
    MANUAL = "MANUAL"
    BULK_UPLOAD = "BULK_UPLOAD"
    EMAIL = "EMAIL"
    CHECKOUT = "CHECKOUT"
    API = "API"
    MISSING_CERTIFICATE = "MISSING_CERTIFICATE"
