"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .countrycodeenum import CountryCodeEnum
from .exemptionsourceenum import ExemptionSourceEnum
from .exemptionstatus import ExemptionStatus
from .exemptiontype import ExemptionType
from datetime import datetime
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict


class ExemptionRequiredTypedDict(TypedDict):
    organization_id: str
    r"""Unique identifier of the organization. This field is deprecated, and should no longer be used. The value is populated through the 'x-organization-id' header."""
    exemption_type: ExemptionType
    start_date: datetime
    status: ExemptionStatus
    reseller: bool
    jurisdiction: NotRequired[Nullable[str]]
    customer_id: NotRequired[Nullable[str]]
    country_code: NotRequired[Nullable[CountryCodeEnum]]
    end_date: NotRequired[Nullable[datetime]]
    fein: NotRequired[Nullable[str]]
    sales_tax_id: NotRequired[Nullable[str]]
    source: NotRequired[Nullable[ExemptionSourceEnum]]


class ExemptionRequired(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]
    r"""Unique identifier of the organization. This field is deprecated, and should no longer be used. The value is populated through the 'x-organization-id' header."""

    exemption_type: ExemptionType

    start_date: datetime

    status: ExemptionStatus

    reseller: bool

    jurisdiction: OptionalNullable[str] = UNSET

    customer_id: OptionalNullable[str] = UNSET

    country_code: OptionalNullable[CountryCodeEnum] = UNSET

    end_date: OptionalNullable[datetime] = UNSET

    fein: Annotated[OptionalNullable[str], pydantic.Field(alias="FEIN")] = UNSET

    sales_tax_id: OptionalNullable[str] = UNSET

    source: OptionalNullable[ExemptionSourceEnum] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "jurisdiction",
                "customer_id",
                "country_code",
                "end_date",
                "FEIN",
                "sales_tax_id",
                "source",
            ]
        )
        nullable_fields = set(
            [
                "jurisdiction",
                "customer_id",
                "country_code",
                "end_date",
                "FEIN",
                "sales_tax_id",
                "source",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ExemptionRequired.model_rebuild()
except NameError:
    pass
