"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class FloridaFieldsTypedDict(TypedDict):
    r"""State-specific fields for Florida (eFile & Pay) registration import.

    Florida requires no 2FA/MFA setup, so there is no ``mfa_completed`` field, and
    the portal grants no customer-facing third-party access step, so there is no
    ``third_party_access_enabled``
    """

    business_name: str
    r"""State-registered business name as shown on the Florida DOR account."""
    fl_certificate_number: str
    r"""Florida Certificate of Registration number (Sales Tax Certificate Number) issued by the Florida Department of Revenue. Also stored as the registration Sales Tax ID."""
    business_partner_number: str
    r"""Florida Business Partner Number: a 7- or 10-digit number assigned by the state. 7-digit values are normalized to 10 digits by prepending three zeros."""
    registration_type: Literal["SALES_TAX"]
    r"""Registration type for this Florida import: sales tax."""


class FloridaFields(BaseModel):
    r"""State-specific fields for Florida (eFile & Pay) registration import.

    Florida requires no 2FA/MFA setup, so there is no ``mfa_completed`` field, and
    the portal grants no customer-facing third-party access step, so there is no
    ``third_party_access_enabled``
    """

    business_name: str
    r"""State-registered business name as shown on the Florida DOR account."""

    fl_certificate_number: str
    r"""Florida Certificate of Registration number (Sales Tax Certificate Number) issued by the Florida Department of Revenue. Also stored as the registration Sales Tax ID."""

    business_partner_number: str
    r"""Florida Business Partner Number: a 7- or 10-digit number assigned by the state. 7-digit values are normalized to 10 digits by prepending three zeros."""

    REGISTRATION_TYPE: Annotated[
        Annotated[Literal["SALES_TAX"], AfterValidator(validate_const("SALES_TAX"))],
        pydantic.Field(alias="registration_type"),
    ] = "SALES_TAX"
    r"""Registration type for this Florida import: sales tax."""


try:
    FloridaFields.model_rebuild()
except NameError:
    pass
