"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .georgiaregistrationtype import GeorgiaRegistrationType
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GeorgiaFieldsTypedDict(TypedDict):
    r"""State-specific fields for Georgia GTC registration import."""

    registration_type: GeorgiaRegistrationType
    business_name: str
    r"""Business name as registered with the state of Georgia."""
    sales_tax_id: str
    r"""Georgia State Tax ID."""
    zip_code: str
    r"""Georgia ZIP code on file with the Georgia Department of Revenue."""
    last_payment_to_state: str
    r"""Last payment amount made to the state ('0.00' if no payments made)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup in their Georgia GTC account."""


class GeorgiaFields(BaseModel):
    r"""State-specific fields for Georgia GTC registration import."""

    registration_type: GeorgiaRegistrationType

    business_name: str
    r"""Business name as registered with the state of Georgia."""

    sales_tax_id: str
    r"""Georgia State Tax ID."""

    zip_code: str
    r"""Georgia ZIP code on file with the Georgia Department of Revenue."""

    last_payment_to_state: str
    r"""Last payment amount made to the state ('0.00' if no payments made)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup in their Georgia GTC account."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
