"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    QueryParamMetadata,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class GetJurisdictionSpecificFieldsV1RegistrationsJurisdictionSpecificFieldsGetRequestTypedDict(
    TypedDict
):
    country_code: str
    r"""ISO 3166-1 alpha-2 country code (e.g., US)."""
    state_code: str
    r"""State/province code (e.g., AL, LA)."""
    x_organization_id: Nullable[str]
    r"""The unique identifier for the organization making the request"""


class GetJurisdictionSpecificFieldsV1RegistrationsJurisdictionSpecificFieldsGetRequest(
    BaseModel
):
    country_code: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""ISO 3166-1 alpha-2 country code (e.g., US)."""

    state_code: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""State/province code (e.g., AL, LA)."""

    x_organization_id: Annotated[
        Nullable[str],
        pydantic.Field(alias="x-organization-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier for the organization making the request"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
