"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetRegistrationByIDV1RegistrationsRegistrationIDGetRequestTypedDict(TypedDict):
    registration_id: str
    r"""The unique identifier of the
    registration to retrieve.
    """
    reveal: NotRequired[str]
    r"""Name of field to reveal"""


class GetRegistrationByIDV1RegistrationsRegistrationIDGetRequest(BaseModel):
    registration_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier of the
    registration to retrieve.
    """

    reveal: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Name of field to reveal"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["reveal"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
