"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .hawaiiregistrationtype import HawaiiRegistrationType
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HawaiiFieldsTypedDict(TypedDict):
    r"""State-specific fields for Hawaii Revenue Online registration import."""

    registration_type: HawaiiRegistrationType
    business_name: str
    r"""Business name as registered with the state of Hawaii."""
    sales_tax_id: str
    r"""Hawaii State Tax ID."""
    letter_id: str
    r"""Any Letter ID except the one on the initial welcome letter. Use the Letter ID from the separate letter sent after registration is complete, or from your online Hawaii tax account."""
    last_payment_to_state: str
    r"""Last payment amount made to the state ('0.00' if no payments made)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup in their Hawaii tax account."""


class HawaiiFields(BaseModel):
    r"""State-specific fields for Hawaii Revenue Online registration import."""

    registration_type: HawaiiRegistrationType

    business_name: str
    r"""Business name as registered with the state of Hawaii."""

    sales_tax_id: str
    r"""Hawaii State Tax ID."""

    letter_id: str
    r"""Any Letter ID except the one on the initial welcome letter. Use the Letter ID from the separate letter sent after registration is complete, or from your online Hawaii tax account."""

    last_payment_to_state: str
    r"""Last payment amount made to the state ('0.00' if no payments made)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup in their Hawaii tax account."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
