"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class IllinoisRegistrationType(str, Enum):
    SALES_AND_USE_TAX = "SALES_AND_USE_TAX"
