"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .kentuckyregistrationtype import KentuckyRegistrationType
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KentuckyFieldsTypedDict(TypedDict):
    r"""State-specific fields for Kentucky KYDOR (MyTaxes) portal registration import."""

    registration_type: KentuckyRegistrationType
    business_name: str
    r"""State-registered business name as shown in Kentucky MyTaxes."""
    ky_state_tax_id: str
    r"""Kentucky state-issued tax identification number (KY State Tax ID)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Kentucky KYDOR (MyTaxes) account."""
    registered_via_sst: NotRequired[bool]
    r"""Whether the business is registered via Streamlined Sales Tax (SST)."""
    sst_account_number: NotRequired[Nullable[str]]
    r"""SST account number; required only when registered_via_sst is True."""
    third_party_access_enabled: NotRequired[bool]
    r"""Whether third-party access has been granted to Kintsugi in KYDOR (MyTaxes)."""


class KentuckyFields(BaseModel):
    r"""State-specific fields for Kentucky KYDOR (MyTaxes) portal registration import."""

    registration_type: KentuckyRegistrationType

    business_name: str
    r"""State-registered business name as shown in Kentucky MyTaxes."""

    ky_state_tax_id: str
    r"""Kentucky state-issued tax identification number (KY State Tax ID)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Kentucky KYDOR (MyTaxes) account."""

    registered_via_sst: Optional[bool] = False
    r"""Whether the business is registered via Streamlined Sales Tax (SST)."""

    sst_account_number: OptionalNullable[str] = UNSET
    r"""SST account number; required only when registered_via_sst is True."""

    third_party_access_enabled: Optional[bool] = False
    r"""Whether third-party access has been granted to Kintsugi in KYDOR (MyTaxes)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "mfa_completed",
                "registered_via_sst",
                "sst_account_number",
                "third_party_access_enabled",
            ]
        )
        nullable_fields = set(["sst_account_number"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
