"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mississippiaccounttype import MississippiAccountType
from .mississippiregistrationtype import MississippiRegistrationType
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class MississippiFieldsTypedDict(TypedDict):
    r"""State-specific fields for Mississippi TAP portal registration import."""

    registration_type: MississippiRegistrationType
    business_name: str
    r"""State-registered business name as shown in Mississippi TAP."""
    ms_state_tax_id: str
    r"""Mississippi Customer Account ID (MS State Tax ID): 8 digits, typically written as 0000-0000."""
    ms_account_type: MississippiAccountType
    letter_id: str
    r"""Letter ID printed on correspondence from the Mississippi Department of Revenue."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Mississippi TAP account."""
    third_party_access_enabled: NotRequired[bool]
    r"""Whether third-party access has been granted to Kintsugi in Mississippi TAP. Customers are informed via footer copy; Kintsugi implements access on their behalf."""


class MississippiFields(BaseModel):
    r"""State-specific fields for Mississippi TAP portal registration import."""

    registration_type: MississippiRegistrationType

    business_name: str
    r"""State-registered business name as shown in Mississippi TAP."""

    ms_state_tax_id: str
    r"""Mississippi Customer Account ID (MS State Tax ID): 8 digits, typically written as 0000-0000."""

    ms_account_type: MississippiAccountType

    letter_id: str
    r"""Letter ID printed on correspondence from the Mississippi Department of Revenue."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Mississippi TAP account."""

    third_party_access_enabled: Optional[bool] = False
    r"""Whether third-party access has been granted to Kintsugi in Mississippi TAP. Customers are informed via footer copy; Kintsugi implements access on their behalf."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed", "third_party_access_enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
