"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class NevadaFieldsTypedDict(TypedDict):
    r"""State-specific fields for Nevada (My Nevada Tax) registration import."""

    business_name: str
    r"""State-registered business name as shown in My Nevada Tax."""
    nv_state_tax_id: str
    r"""Nevada state-issued tax identification number (NV State Tax ID)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Nevada tax account."""
    registration_type: Literal["SALES_AND_USE_TAX"]
    r"""Registration type for this Nevada import: sales and use tax."""


class NevadaFields(BaseModel):
    r"""State-specific fields for Nevada (My Nevada Tax) registration import."""

    business_name: str
    r"""State-registered business name as shown in My Nevada Tax."""

    nv_state_tax_id: str
    r"""Nevada state-issued tax identification number (NV State Tax ID)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Nevada tax account."""

    REGISTRATION_TYPE: Annotated[
        Annotated[
            Literal["SALES_AND_USE_TAX"],
            AfterValidator(validate_const("SALES_AND_USE_TAX")),
        ],
        pydantic.Field(alias="registration_type"),
    ] = "SALES_AND_USE_TAX"
    r"""Registration type for this Nevada import: sales and use tax."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    NevadaFields.model_rebuild()
except NameError:
    pass
