"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class NewYorkFieldsTypedDict(TypedDict):
    r"""State-specific fields for New York (NYS Tax) registration import.

    New York requires no 2FA/MFA setup, so there is no ``mfa_completed`` field,
    and it grants no customer-facing third-party access step, so there is no
    ``third_party_access_enabled`` field either.
    """

    business_name: str
    r"""State-registered business name as shown on the New York tax account."""
    ny_state_tax_id: str
    r"""NY State Tax ID: 9-digit state certificate number (normally the Federal Tax ID), or TF followed by 7 digits for sole proprietors (e.g. 123456789 or TF1234567)."""
    registration_type: Literal["SALES_AND_USE_TAX"]
    r"""Registration type for this New York import: sales and use tax."""


class NewYorkFields(BaseModel):
    r"""State-specific fields for New York (NYS Tax) registration import.

    New York requires no 2FA/MFA setup, so there is no ``mfa_completed`` field,
    and it grants no customer-facing third-party access step, so there is no
    ``third_party_access_enabled`` field either.
    """

    business_name: str
    r"""State-registered business name as shown on the New York tax account."""

    ny_state_tax_id: str
    r"""NY State Tax ID: 9-digit state certificate number (normally the Federal Tax ID), or TF followed by 7 digits for sole proprietors (e.g. 123456789 or TF1234567)."""

    REGISTRATION_TYPE: Annotated[
        Annotated[
            Literal["SALES_AND_USE_TAX"],
            AfterValidator(validate_const("SALES_AND_USE_TAX")),
        ],
        pydantic.Field(alias="registration_type"),
    ] = "SALES_AND_USE_TAX"
    r"""Registration type for this New York import: sales and use tax."""


try:
    NewYorkFields.model_rebuild()
except NameError:
    pass
