"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .countrycodeenum import CountryCodeEnum
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class OSSRegistrationCreatePayloadTypedDict(TypedDict):
    registration_import_type: NotRequired[str]
    r"""Specifies this is an OSS registration import."""
    password_plain_text: NotRequired[str]
    r"""The plaintext password for accessing the tax registration account."""
    password_metadata_plain_text: NotRequired[str]
    r"""Metadata related to the password."""
    member_state_of_identification_code: NotRequired[CountryCodeEnum]
    imported: NotRequired[bool]
    r"""Whether the registration was imported from another system."""


class OSSRegistrationCreatePayload(BaseModel):
    registration_import_type: Optional[str] = "OSS"
    r"""Specifies this is an OSS registration import."""

    password_plain_text: Optional[str] = None
    r"""The plaintext password for accessing the tax registration account."""

    password_metadata_plain_text: Optional[str] = None
    r"""Metadata related to the password."""

    member_state_of_identification_code: Optional[CountryCodeEnum] = None

    imported: Optional[bool] = False
    r"""Whether the registration was imported from another system."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "registration_import_type",
                "password_plain_text",
                "password_metadata_plain_text",
                "member_state_of_identification_code",
                "imported",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
