"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .countrycodeenum import CountryCodeEnum
from .osscountrystatusenum import OssCountryStatusEnum
from datetime import date
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class OssRegistrationCountryReadTypedDict(TypedDict):
    id: str
    r"""The unique identifier for the OSS registration country."""
    country_code: CountryCodeEnum
    effective_date: date
    r"""The date from which this country is officially covered by the OSS registration."""
    status: OssCountryStatusEnum
    r"""Status of a country within an OSS registration.

    Keep the members in sync with ``PublicOssCountryStatusEnum``: the tenanted API
    projects this onto that public enum by value (``_to_public_oss_country`` in
    ``registrations/routers/latest.py``), so a member added here without a matching
    public member raises ``ValueError`` and 500s the tenanted read for any row carrying
    the new status. Add it to both, or map it deliberately at the projection.
    """
    end_date: NotRequired[Nullable[date]]
    r"""The date this country ceased to be covered by the OSS registration (if applicable)."""


class OssRegistrationCountryRead(BaseModel):
    id: str
    r"""The unique identifier for the OSS registration country."""

    country_code: CountryCodeEnum

    effective_date: date
    r"""The date from which this country is officially covered by the OSS registration."""

    status: OssCountryStatusEnum
    r"""Status of a country within an OSS registration.

    Keep the members in sync with ``PublicOssCountryStatusEnum``: the tenanted API
    projects this onto that public enum by value (``_to_public_oss_country`` in
    ``registrations/routers/latest.py``), so a member added here without a matching
    public member raises ``ValueError`` and 500s the tenanted read for any row carrying
    the new status. Add it to both, or map it deliberately at the projection.
    """

    end_date: OptionalNullable[date] = UNSET
    r"""The date this country ceased to be covered by the OSS registration (if applicable)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["end_date"])
        nullable_fields = set(["end_date"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
