"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .transactionestimateresponse import (
    TransactionEstimateResponse,
    TransactionEstimateResponseTypedDict,
)
from kintsugi_tax_platform_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PageTransactionEstimateResponseTypedDict(TypedDict):
    items: List[TransactionEstimateResponseTypedDict]
    total: int
    page: int
    size: int
    pages: int


class PageTransactionEstimateResponse(BaseModel):
    items: List[TransactionEstimateResponse]

    total: int

    page: int

    size: int

    pages: int
