"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filingread import FilingRead, FilingReadTypedDict
from kintsugi_tax_platform_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PageFilingReadTypedDict(TypedDict):
    items: List[FilingReadTypedDict]
    total: int
    page: int
    size: int
    pages: int


class PageFilingRead(BaseModel):
    items: List[FilingRead]

    total: int

    page: int

    size: int

    pages: int
