"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .nexusresponse import NexusResponse, NexusResponseTypedDict
from kintsugi_tax_platform_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PageNexusResponseTypedDict(TypedDict):
    items: List[NexusResponseTypedDict]
    total: int
    page: int
    size: int
    pages: int


class PageNexusResponse(BaseModel):
    items: List[NexusResponse]

    total: int

    page: int

    size: int

    pages: int
