"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PennsylvaniaAccountType(str, Enum):
    r"""Account ID types accepted when requesting third-party access on Pennsylvania myPATH.

    myPATH identifies the account by one of these: a Business Use ID, an Account ID,
    or a Sales License ID.
    """

    BUSINESS_USE_ID = "BUSINESS_USE_ID"
    ACCOUNT_ID = "ACCOUNT_ID"
    SALES_LICENSE_ID = "SALES_LICENSE_ID"
