"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PennsylvaniaAccountValidationMethod(str, Enum):
    r"""Account validation methods offered by Pennsylvania myPATH third-party access.

    The requester proves ownership with exactly one of these: a Letter ID, a Business
    Registration Confirmation Code, a Payment Amount, or a Return Line Item.
    """

    LETTER_ID = "LETTER_ID"
    BUSINESS_REGISTRATION_CONFIRMATION_CODE = "BUSINESS_REGISTRATION_CONFIRMATION_CODE"
    PAYMENT_AMOUNT = "PAYMENT_AMOUNT"
    RETURN_LINE_ITEM = "RETURN_LINE_ITEM"
