"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .physicalnexuscategory import PhysicalNexusCategory
from datetime import date
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class PhysicalNexusUpdateTypedDict(TypedDict):
    start_date: date
    r"""The date when the nexus became
    effective (YYYY-MM-DD).
    """
    category: PhysicalNexusCategory
    end_date: NotRequired[Nullable[date]]
    r"""The date when the
    nexus ends, if applicable (YYYY-MM-DD).
    """
    street_1: NotRequired[Nullable[str]]
    r"""Primary street address for the physical presence location."""
    street_2: NotRequired[Nullable[str]]
    r"""Additional street address details, such as suite or unit number."""
    city: NotRequired[Nullable[str]]
    r"""City of the physical presence location."""
    postal_code: NotRequired[Nullable[str]]
    r"""ZIP or postal code of the physical presence location."""


class PhysicalNexusUpdate(BaseModel):
    start_date: date
    r"""The date when the nexus became
    effective (YYYY-MM-DD).
    """

    category: PhysicalNexusCategory

    end_date: OptionalNullable[date] = UNSET
    r"""The date when the
    nexus ends, if applicable (YYYY-MM-DD).
    """

    street_1: OptionalNullable[str] = UNSET
    r"""Primary street address for the physical presence location."""

    street_2: OptionalNullable[str] = UNSET
    r"""Additional street address details, such as suite or unit number."""

    city: OptionalNullable[str] = UNSET
    r"""City of the physical presence location."""

    postal_code: OptionalNullable[str] = UNSET
    r"""ZIP or postal code of the physical presence location."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["end_date", "street_1", "street_2", "city", "postal_code"]
        )
        nullable_fields = set(
            ["end_date", "street_1", "street_2", "city", "postal_code"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
