"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from typing_extensions import TypedDict


class PhysicalNexusCategoriesTypedDict(TypedDict):
    name: str
    title: str
    description: str
    example: str
    is_category_assigned: bool


class PhysicalNexusCategories(BaseModel):
    name: str

    title: str

    description: str

    example: str

    is_category_assigned: bool
