"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productstatusenum import ProductStatusEnum
from .sourceenum import SourceEnum
from kintsugi_tax_platform_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ProductReadTypedDict(TypedDict):
    id: str
    external_id: str
    sku: List[str]
    code: str
    name: str
    description: str
    status: ProductStatusEnum
    product_category: str
    product_subcategory: str
    tax_exempt: bool
    source: SourceEnum
    connection_id: str
    classification_failed: bool


class ProductRead(BaseModel):
    id: str

    external_id: str

    sku: List[str]

    code: str

    name: str

    description: str

    status: ProductStatusEnum

    product_category: str

    product_subcategory: str

    tax_exempt: bool

    source: SourceEnum

    connection_id: str

    classification_failed: bool
