"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productstatusenum import ProductStatusEnum
from .sourceenum import SourceEnum
from kintsugi_tax_platform_sdk.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ProductReadTypedDict(TypedDict):
    id: str
    external_id: str
    sku: List[str]
    code: str
    name: str
    description: str
    status: ProductStatusEnum
    product_category: str
    r"""Main category of the product.
    For example, Physical, Digital, etc. You can
    retrieve supported categories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """
    product_subcategory: str
    r"""Subcategory of the product.
    For example, General Clothing, UNKNOWN, etc. You can
    retrieve supported subcategories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """
    tax_exempt: bool
    source: SourceEnum
    connection_id: str
    classification_failed: bool


class ProductRead(BaseModel):
    id: str

    external_id: str

    sku: List[str]

    code: str

    name: str

    description: str

    status: ProductStatusEnum

    product_category: str
    r"""Main category of the product.
    For example, Physical, Digital, etc. You can
    retrieve supported categories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """

    product_subcategory: str
    r"""Subcategory of the product.
    For example, General Clothing, UNKNOWN, etc. You can
    retrieve supported subcategories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """

    tax_exempt: bool

    source: SourceEnum

    connection_id: str

    classification_failed: bool
