"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .productstatusenum import ProductStatusEnum
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ProductUpdateTypedDict(TypedDict):
    name: str
    r"""Name of the product."""
    product_category: str
    r"""Main category of the product.
    For example, Physical, Digital, etc. You can
    retrieve supported categories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """
    product_subcategory: str
    r"""Subcategory of the product.
    For example, General Clothing, UNKNOWN, etc. You can
    retrieve supported subcategories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """
    tax_exempt: bool
    r"""Indicates whether the product is tax-exempt."""
    id: NotRequired[str]
    r"""The unique identifier of the product to be updated."""
    external_id: NotRequired[str]
    r"""External identifier provided for the product,
    typically by the source system.
    """
    sku: NotRequired[List[str]]
    description: NotRequired[str]
    r"""Description of the product."""
    status: NotRequired[ProductStatusEnum]
    classification_failed: NotRequired[bool]
    r"""Indicates if the product classification failed."""


class ProductUpdate(BaseModel):
    name: str
    r"""Name of the product."""

    product_category: str
    r"""Main category of the product.
    For example, Physical, Digital, etc. You can
    retrieve supported categories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """

    product_subcategory: str
    r"""Subcategory of the product.
    For example, General Clothing, UNKNOWN, etc. You can
    retrieve supported subcategories from [GET /products/categories endpoint](/reference/api/products/get-product-categories)
    """

    tax_exempt: bool
    r"""Indicates whether the product is tax-exempt."""

    id: Optional[str] = None
    r"""The unique identifier of the product to be updated."""

    external_id: Optional[str] = None
    r"""External identifier provided for the product,
    typically by the source system.
    """

    sku: Optional[List[str]] = None

    description: Optional[str] = None
    r"""Description of the product."""

    status: Optional[ProductStatusEnum] = None

    classification_failed: Optional[bool] = False
    r"""Indicates if the product classification failed."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "external_id",
                "sku",
                "description",
                "status",
                "classification_failed",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
