"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .quarterlyprepaydeduction import (
    QuarterlyPrepayDeduction,
    QuarterlyPrepayDeductionTypedDict,
)
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class QuarterlyPrepayBalanceDisplayTypedDict(TypedDict):
    r"""Display-only balance-due breakdown for CA Quarterly Prepayment reconciliation.

    Populated only when the org has ``enable_ca_qp_tax_liability_display`` on and the
    filing is a CA ``QUARTERLY_PREPAYMENT`` ``REGULAR`` reconciliation with prepayment
    siblings. Does not change any stored amount on the filing.
    """

    gross_tax_liability: str
    r"""The filing's stored full-quarter total_tax_liability."""
    balance_due: str
    r"""gross_tax_liability minus the sum of prepayment deductions."""
    prepayment_deductions: NotRequired[List[QuarterlyPrepayDeductionTypedDict]]
    r"""The monthly prepayments netted out, ordered by period."""


class QuarterlyPrepayBalanceDisplay(BaseModel):
    r"""Display-only balance-due breakdown for CA Quarterly Prepayment reconciliation.

    Populated only when the org has ``enable_ca_qp_tax_liability_display`` on and the
    filing is a CA ``QUARTERLY_PREPAYMENT`` ``REGULAR`` reconciliation with prepayment
    siblings. Does not change any stored amount on the filing.
    """

    gross_tax_liability: str
    r"""The filing's stored full-quarter total_tax_liability."""

    balance_due: str
    r"""gross_tax_liability minus the sum of prepayment deductions."""

    prepayment_deductions: Optional[List[QuarterlyPrepayDeduction]] = None
    r"""The monthly prepayments netted out, ordered by period."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["prepayment_deductions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
