"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from typing_extensions import TypedDict


class RegistrationJurisdictionOptionReadTypedDict(TypedDict):
    r"""One distinct (country, state) jurisdiction for listings and filters."""

    country_code: str
    r"""ISO 3166-1 alpha-2 country code (e.g. US, DE)."""
    state_code: str
    r"""State or province code (may be empty for country-level rows)."""
    state_name: str
    r"""Display name for the state or province."""


class RegistrationJurisdictionOptionRead(BaseModel):
    r"""One distinct (country, state) jurisdiction for listings and filters."""

    country_code: str
    r"""ISO 3166-1 alpha-2 country code (e.g. US, DE)."""

    state_code: str
    r"""State or province code (may be empty for country-level rows)."""

    state_name: str
    r"""Display name for the state or province."""
