"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .changeregimestatusenum import ChangeRegimeStatusEnum
from .countrycodeenum import CountryCodeEnum
from .filingfrequencyenum import FilingFrequencyEnum
from .osstypeenum import OssTypeEnum
from .registrationcategoryenum import RegistrationCategoryEnum
from .registrationsregimeenum import RegistrationsRegimeEnum
from .registrationstatusenum import RegistrationStatusEnum
from .registrationtypeenum import RegistrationTypeEnum
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RegistrationReadTypedDict(TypedDict):
    status: RegistrationStatusEnum
    country_code: CountryCodeEnum
    state_code: str
    r"""The state/province code where the registration applies."""
    state_name: str
    r"""The name of the state/province."""
    filing_frequency: FilingFrequencyEnum
    id: str
    r"""The unique identifier for the registration."""
    filing_days: int
    registration_type: RegistrationTypeEnum
    registration_date: NotRequired[str]
    r"""The date when the registration was created. Format: YYYY-MM-DD."""
    registration_email: NotRequired[str]
    r"""Email address associated with the registration."""
    registration_key: NotRequired[str]
    r"""A unique key assigned to the registration."""
    deregistration_key: NotRequired[str]
    r"""A unique key assigned for deregistration."""
    registration_requested: NotRequired[str]
    r"""Timestamp when the registration was requested."""
    registration_completed: NotRequired[str]
    r"""Timestamp when the registration was completed."""
    deregistration_requested: NotRequired[str]
    r"""Timestamp when deregistration was requested."""
    deregistration_completed: NotRequired[str]
    r"""Timestamp when the deregistration was completed."""
    auto_registered: NotRequired[bool]
    r"""Indicates whether the registration was completed automatically."""
    registrations_regime: NotRequired[RegistrationsRegimeEnum]
    change_regime_status: NotRequired[ChangeRegimeStatusEnum]
    third_party_enabled: NotRequired[bool]
    r"""Indicates whether third-party access is enabled for this registration."""
    do_not_file: NotRequired[bool]
    r"""If true, do not file for this registration (treated as False by default)."""
    two_factor_enabled: NotRequired[bool]
    r"""Indicates whether two-factor authentication (2FA) is enabled for this registration."""
    marked_collecting: NotRequired[bool]
    r"""Indicates whether the  registration is marked as collecting in shopify"""
    username: NotRequired[str]
    r"""Username for accessing tax registration details."""
    comment: NotRequired[str]
    r"""Additional comments related to the registration."""
    create_filings_from: NotRequired[str]
    r"""The date from which filings should be created.
    should start (YYYY-MM-DD).
    """
    initial_sync: NotRequired[bool]
    r"""Indicates whether an initial synchronization should be performed."""
    amount_fees: NotRequired[str]
    r"""The amount of fees associated with the registration."""
    vda: NotRequired[bool]
    r"""Indicates whether a Voluntary Disclosure Agreement (VDA) applies."""
    imported: NotRequired[bool]
    r"""Whether the registration was imported from another system."""
    sales_tax_id: NotRequired[str]
    r"""The sales tax ID associated with the registration."""
    sst_import: NotRequired[bool]
    r"""Indicates whether the registration is an SST Import."""
    oss_type: NotRequired[OssTypeEnum]
    r"""Type of OSS registration."""
    oss_member_state_of_identification_code: NotRequired[CountryCodeEnum]
    marked_collecting_date: NotRequired[str]
    r"""The date when the registration was marked as collecting."""
    needs_mark_as_collecting: NotRequired[bool]
    r"""Indicates whether the registration needs to be marked as collecting."""
    credits_total_available: NotRequired[str]
    registration_category: NotRequired[RegistrationCategoryEnum]


class RegistrationRead(BaseModel):
    status: RegistrationStatusEnum

    country_code: CountryCodeEnum

    state_code: str
    r"""The state/province code where the registration applies."""

    state_name: str
    r"""The name of the state/province."""

    filing_frequency: FilingFrequencyEnum

    id: str
    r"""The unique identifier for the registration."""

    filing_days: int

    registration_type: RegistrationTypeEnum

    registration_date: Optional[str] = None
    r"""The date when the registration was created. Format: YYYY-MM-DD."""

    registration_email: Optional[str] = None
    r"""Email address associated with the registration."""

    registration_key: Optional[str] = None
    r"""A unique key assigned to the registration."""

    deregistration_key: Optional[str] = None
    r"""A unique key assigned for deregistration."""

    registration_requested: Optional[str] = None
    r"""Timestamp when the registration was requested."""

    registration_completed: Optional[str] = None
    r"""Timestamp when the registration was completed."""

    deregistration_requested: Optional[str] = None
    r"""Timestamp when deregistration was requested."""

    deregistration_completed: Optional[str] = None
    r"""Timestamp when the deregistration was completed."""

    auto_registered: Optional[bool] = False
    r"""Indicates whether the registration was completed automatically."""

    registrations_regime: Optional[RegistrationsRegimeEnum] = None

    change_regime_status: Optional[ChangeRegimeStatusEnum] = None

    third_party_enabled: Optional[bool] = False
    r"""Indicates whether third-party access is enabled for this registration."""

    do_not_file: Optional[bool] = False
    r"""If true, do not file for this registration (treated as False by default)."""

    two_factor_enabled: Optional[bool] = None
    r"""Indicates whether two-factor authentication (2FA) is enabled for this registration."""

    marked_collecting: Optional[bool] = None
    r"""Indicates whether the  registration is marked as collecting in shopify"""

    username: Optional[str] = None
    r"""Username for accessing tax registration details."""

    comment: Optional[str] = None
    r"""Additional comments related to the registration."""

    create_filings_from: Optional[str] = None
    r"""The date from which filings should be created.
    should start (YYYY-MM-DD).
    """

    initial_sync: Optional[bool] = False
    r"""Indicates whether an initial synchronization should be performed."""

    amount_fees: Optional[str] = "0.00"
    r"""The amount of fees associated with the registration."""

    vda: Optional[bool] = False
    r"""Indicates whether a Voluntary Disclosure Agreement (VDA) applies."""

    imported: Optional[bool] = None
    r"""Whether the registration was imported from another system."""

    sales_tax_id: Optional[str] = None
    r"""The sales tax ID associated with the registration."""

    sst_import: Optional[bool] = False
    r"""Indicates whether the registration is an SST Import."""

    oss_type: Optional[OssTypeEnum] = None
    r"""Type of OSS registration."""

    oss_member_state_of_identification_code: Optional[CountryCodeEnum] = None

    marked_collecting_date: Optional[str] = None
    r"""The date when the registration was marked as collecting."""

    needs_mark_as_collecting: Optional[bool] = False
    r"""Indicates whether the registration needs to be marked as collecting."""

    credits_total_available: Optional[str] = "0.00"

    registration_category: Optional[RegistrationCategoryEnum] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "registration_date",
                "registration_email",
                "registration_key",
                "deregistration_key",
                "registration_requested",
                "registration_completed",
                "deregistration_requested",
                "deregistration_completed",
                "auto_registered",
                "registrations_regime",
                "change_regime_status",
                "third_party_enabled",
                "do_not_file",
                "two_factor_enabled",
                "marked_collecting",
                "username",
                "comment",
                "create_filings_from",
                "initial_sync",
                "amount_fees",
                "vda",
                "imported",
                "sales_tax_id",
                "sst_import",
                "oss_type",
                "oss_member_state_of_identification_code",
                "marked_collecting_date",
                "needs_mark_as_collecting",
                "credits_total_available",
                "registration_category",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
