"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SouthCarolinaFieldsTypedDict(TypedDict):
    r"""State-specific fields for South Carolina (MyDORWAY) registration import."""

    business_name: str
    r"""State-registered business name as shown in MyDORWAY."""
    sc_state_tax_id: str
    r"""South Carolina state-issued tax identification number (SC State Tax ID)."""
    sc_sid: str
    r"""South Carolina SID (Single Identification Number): 8 digits assigned by the state for filing returns."""
    letter_id: str
    r"""Unique number printed on all correspondence from the SC Department of Revenue. Begins with an L (format: L followed by 10 digits, e.g. L9999999999)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their South Carolina tax account."""
    registration_type: Literal["RETAIL_SALES_TAX"]
    r"""Registration type for this South Carolina import: retail sales tax."""


class SouthCarolinaFields(BaseModel):
    r"""State-specific fields for South Carolina (MyDORWAY) registration import."""

    business_name: str
    r"""State-registered business name as shown in MyDORWAY."""

    sc_state_tax_id: str
    r"""South Carolina state-issued tax identification number (SC State Tax ID)."""

    sc_sid: str
    r"""South Carolina SID (Single Identification Number): 8 digits assigned by the state for filing returns."""

    letter_id: str
    r"""Unique number printed on all correspondence from the SC Department of Revenue. Begins with an L (format: L followed by 10 digits, e.g. L9999999999)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their South Carolina tax account."""

    REGISTRATION_TYPE: Annotated[
        Annotated[
            Literal["RETAIL_SALES_TAX"],
            AfterValidator(validate_const("RETAIL_SALES_TAX")),
        ],
        pydantic.Field(alias="registration_type"),
    ] = "RETAIL_SALES_TAX"
    r"""Registration type for this South Carolina import: retail sales tax."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    SouthCarolinaFields.model_rebuild()
except NameError:
    pass
