"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .taxitemreturnreasonenum import TaxItemReturnReasonEnum
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TaxItemEstimateTypedDict(TypedDict):
    name: str
    rate: NotRequired[str]
    amount: NotRequired[str]
    exempt: NotRequired[bool]
    exempt_reason: NotRequired[Nullable[TaxItemReturnReasonEnum]]
    rule: NotRequired[Nullable[str]]


class TaxItemEstimate(BaseModel):
    name: str

    rate: Optional[str] = "0.0"

    amount: Optional[str] = "0.0"

    exempt: Optional[bool] = False

    exempt_reason: OptionalNullable[TaxItemReturnReasonEnum] = UNSET

    rule: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["rate", "amount", "exempt", "exempt_reason", "rule"])
        nullable_fields = set(["exempt_reason", "rule"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
