"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .tennesseeregistrationtype import TennesseeRegistrationType
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TennesseeFieldsTypedDict(TypedDict):
    r"""State-specific fields for Tennessee TNTAP portal registration import."""

    registration_type: TennesseeRegistrationType
    business_name: str
    r"""State-registered business name as shown in TNTAP."""
    tn_state_tax_id: str
    r"""Tennessee state-issued tax identification number (TN State Tax ID)."""
    zip_code: str
    r"""Account ZIP code on file with the Tennessee Department of Revenue."""
    letter_id: str
    r"""Tennessee Letter ID printed on correspondence from the TN Department of Revenue: prefix L followed by 10 digits (e.g. L1234567890)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Tennessee DOR TNTAP account."""


class TennesseeFields(BaseModel):
    r"""State-specific fields for Tennessee TNTAP portal registration import."""

    registration_type: TennesseeRegistrationType

    business_name: str
    r"""State-registered business name as shown in TNTAP."""

    tn_state_tax_id: str
    r"""Tennessee state-issued tax identification number (TN State Tax ID)."""

    zip_code: str
    r"""Account ZIP code on file with the Tennessee Department of Revenue."""

    letter_id: str
    r"""Tennessee Letter ID printed on correspondence from the TN Department of Revenue: prefix L followed by 10 digits (e.g. L1234567890)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their Tennessee DOR TNTAP account."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
