"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .countrycodeenum import CountryCodeEnum
from .currencyenum import CurrencyEnum
from .customerupdate import CustomerUpdate, CustomerUpdateTypedDict
from .documenttypeenum import DocumentTypeEnum
from .exemptionrequired import ExemptionRequired, ExemptionRequiredTypedDict
from .sourceenum import SourceEnum
from .taxliabilitysourceenum import TaxLiabilitySourceEnum
from .transactionaddress_input import (
    TransactionAddressInput,
    TransactionAddressInputTypedDict,
)
from .transactionaddressbuilder import (
    TransactionAddressBuilder,
    TransactionAddressBuilderTypedDict,
)
from .transactionembeddedexemption import (
    TransactionEmbeddedExemption,
    TransactionEmbeddedExemptionTypedDict,
)
from .transactionexemptstatusenum import TransactionExemptStatusEnum
from .transactionitemcreateupdate import (
    TransactionItemCreateUpdate,
    TransactionItemCreateUpdateTypedDict,
)
from .transactionrefundstatus import TransactionRefundStatus
from .transactionstatusenum import TransactionStatusEnum
from datetime import date, datetime
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


TransactionUpdateTotalAmountTypedDict = TypeAliasType(
    "TransactionUpdateTotalAmountTypedDict", Union[float, str]
)
r"""Total amount of the transaction."""


TransactionUpdateTotalAmount = TypeAliasType(
    "TransactionUpdateTotalAmount", Union[float, str]
)
r"""Total amount of the transaction."""


TransactionUpdateTotalTaxAmountImportedTypedDict = TypeAliasType(
    "TransactionUpdateTotalTaxAmountImportedTypedDict", Union[float, str]
)
r"""Imported tax amount."""


TransactionUpdateTotalTaxAmountImported = TypeAliasType(
    "TransactionUpdateTotalTaxAmountImported", Union[float, str]
)
r"""Imported tax amount."""


TransactionUpdateTaxRateImportedTypedDict = TypeAliasType(
    "TransactionUpdateTaxRateImportedTypedDict", Union[float, str]
)
r"""Imported tax rate."""


TransactionUpdateTaxRateImported = TypeAliasType(
    "TransactionUpdateTaxRateImported", Union[float, str]
)
r"""Imported tax rate."""


TransactionUpdateTotalTaxAmountCalculatedTypedDict = TypeAliasType(
    "TransactionUpdateTotalTaxAmountCalculatedTypedDict", Union[float, str]
)
r"""Calculated tax amount."""


TransactionUpdateTotalTaxAmountCalculated = TypeAliasType(
    "TransactionUpdateTotalTaxAmountCalculated", Union[float, str]
)
r"""Calculated tax amount."""


TransactionUpdateTaxRateCalculatedTypedDict = TypeAliasType(
    "TransactionUpdateTaxRateCalculatedTypedDict", Union[float, str]
)
r"""Calculated tax rate."""


TransactionUpdateTaxRateCalculated = TypeAliasType(
    "TransactionUpdateTaxRateCalculated", Union[float, str]
)
r"""Calculated tax rate."""


TransactionUpdateTotalTaxLiabilityAmountTypedDict = TypeAliasType(
    "TransactionUpdateTotalTaxLiabilityAmountTypedDict", Union[float, str]
)
r"""Total tax liability amount."""


TransactionUpdateTotalTaxLiabilityAmount = TypeAliasType(
    "TransactionUpdateTotalTaxLiabilityAmount", Union[float, str]
)
r"""Total tax liability amount."""


TransactionUpdateTaxableAmountTypedDict = TypeAliasType(
    "TransactionUpdateTaxableAmountTypedDict", Union[float, str]
)
r"""Taxable amount."""


TransactionUpdateTaxableAmount = TypeAliasType(
    "TransactionUpdateTaxableAmount", Union[float, str]
)
r"""Taxable amount."""


TransactionUpdateAddressesTypedDict = TypeAliasType(
    "TransactionUpdateAddressesTypedDict",
    Union[
        List[TransactionAddressBuilderTypedDict], List[TransactionAddressInputTypedDict]
    ],
)


TransactionUpdateAddresses = TypeAliasType(
    "TransactionUpdateAddresses",
    Union[List[TransactionAddressBuilder], List[TransactionAddressInput]],
)


class TransactionUpdateTypedDict(TypedDict):
    organization_id: str
    r"""Unique identifier of the organization. This field is deprecated, and should no longer be used. The value is populated through the 'x-organization-id' header."""
    external_id: str
    r"""External identifier of the transaction."""
    date_: datetime
    r"""Transaction date and time"""
    addresses: TransactionUpdateAddressesTypedDict
    transaction_items: List[TransactionItemCreateUpdateTypedDict]
    customer: CustomerUpdateTypedDict
    requires_exemption: NotRequired[Nullable[ExemptionRequiredTypedDict]]
    r"""Indicates if transaction requires tax exemption."""
    shop_date: NotRequired[Nullable[date]]
    r"""Transaction date in the shop's local timezone"""
    shop_date_tz: NotRequired[Nullable[str]]
    r"""Timezone of the shop"""
    description: NotRequired[Nullable[str]]
    r"""Description of the transaction."""
    refund_status: NotRequired[Nullable[TransactionRefundStatus]]
    r"""Status of refund, if applicable"""
    total_amount: NotRequired[TransactionUpdateTotalAmountTypedDict]
    r"""Total amount of the transaction."""
    customer_id: NotRequired[Nullable[str]]
    r"""Unique identifier of the customer."""
    marketplace: NotRequired[Nullable[bool]]
    r"""Indicates if transaction is marketplace-based."""
    exempt: NotRequired[Nullable[TransactionExemptStatusEnum]]
    r"""Exemption status (e.g., NOT_EXEMPT)"""
    exemptions: NotRequired[Nullable[List[TransactionEmbeddedExemptionTypedDict]]]
    r"""List of exemptions applied (if any)."""
    related_to: NotRequired[Nullable[str]]
    r"""Related transaction identifier."""
    secondary_external_id: NotRequired[Nullable[str]]
    r"""Secondary External Identifier."""
    secondary_source: NotRequired[Nullable[str]]
    r"""Secondary source information"""
    external_friendly_id: NotRequired[Nullable[str]]
    r"""Friendly identifier of the original item."""
    total_tax_amount_imported: NotRequired[
        TransactionUpdateTotalTaxAmountImportedTypedDict
    ]
    r"""Imported tax amount."""
    tax_rate_imported: NotRequired[TransactionUpdateTaxRateImportedTypedDict]
    r"""Imported tax rate."""
    total_tax_amount_calculated: NotRequired[
        TransactionUpdateTotalTaxAmountCalculatedTypedDict
    ]
    r"""Calculated tax amount."""
    tax_rate_calculated: NotRequired[TransactionUpdateTaxRateCalculatedTypedDict]
    r"""Calculated tax rate."""
    total_tax_liability_amount: NotRequired[
        TransactionUpdateTotalTaxLiabilityAmountTypedDict
    ]
    r"""Total tax liability amount."""
    tax_liability_source: NotRequired[Nullable[TaxLiabilitySourceEnum]]
    r"""Source of tax liability."""
    taxable_amount: NotRequired[TransactionUpdateTaxableAmountTypedDict]
    r"""Taxable amount."""
    currency: NotRequired[CurrencyEnum]
    r"""ISO-4217 currency code. Pair with a monetary amount on the same object."""
    locked: NotRequired[bool]
    r"""Transaction lock status."""
    source: NotRequired[SourceEnum]
    connection_id: NotRequired[Nullable[str]]
    r"""Connection Identifier"""
    filing_id: NotRequired[Nullable[str]]
    r"""Filing identifier."""
    city: NotRequired[Nullable[str]]
    r"""City of the transaction address."""
    county: NotRequired[Nullable[str]]
    r"""County of the transaction address."""
    state: NotRequired[Nullable[str]]
    r"""State of the transaction address."""
    country: NotRequired[Nullable[CountryCodeEnum]]
    r"""Country code (ISO Alpha-2)."""
    postal_code: NotRequired[Nullable[str]]
    r"""Postal code of the transaction."""
    tax_id: NotRequired[Nullable[str]]
    r"""Tax ID associated with the transaction. DEPRECATED: This field is only populated for QuickBooks integrations and will be removed in a future version."""
    status: NotRequired[TransactionStatusEnum]
    document_type: NotRequired[Nullable[DocumentTypeEnum]]
    r"""Document type distinguishing invoices from sales orders."""
    created_from: NotRequired[Nullable[str]]
    r"""Identifier of the invoice that created from a sales order."""


class TransactionUpdate(BaseModel):
    organization_id: Annotated[
        str,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]
    r"""Unique identifier of the organization. This field is deprecated, and should no longer be used. The value is populated through the 'x-organization-id' header."""

    external_id: str
    r"""External identifier of the transaction."""

    date_: Annotated[datetime, pydantic.Field(alias="date")]
    r"""Transaction date and time"""

    addresses: TransactionUpdateAddresses

    transaction_items: List[TransactionItemCreateUpdate]

    customer: CustomerUpdate

    requires_exemption: OptionalNullable[ExemptionRequired] = UNSET
    r"""Indicates if transaction requires tax exemption."""

    shop_date: OptionalNullable[date] = UNSET
    r"""Transaction date in the shop's local timezone"""

    shop_date_tz: OptionalNullable[str] = UNSET
    r"""Timezone of the shop"""

    description: OptionalNullable[str] = UNSET
    r"""Description of the transaction."""

    refund_status: OptionalNullable[TransactionRefundStatus] = UNSET
    r"""Status of refund, if applicable"""

    total_amount: Optional[TransactionUpdateTotalAmount] = None
    r"""Total amount of the transaction."""

    customer_id: OptionalNullable[str] = UNSET
    r"""Unique identifier of the customer."""

    marketplace: OptionalNullable[bool] = UNSET
    r"""Indicates if transaction is marketplace-based."""

    exempt: OptionalNullable[TransactionExemptStatusEnum] = UNSET
    r"""Exemption status (e.g., NOT_EXEMPT)"""

    exemptions: OptionalNullable[List[TransactionEmbeddedExemption]] = UNSET
    r"""List of exemptions applied (if any)."""

    related_to: OptionalNullable[str] = UNSET
    r"""Related transaction identifier."""

    secondary_external_id: OptionalNullable[str] = UNSET
    r"""Secondary External Identifier."""

    secondary_source: OptionalNullable[str] = UNSET
    r"""Secondary source information"""

    external_friendly_id: OptionalNullable[str] = UNSET
    r"""Friendly identifier of the original item."""

    total_tax_amount_imported: Optional[TransactionUpdateTotalTaxAmountImported] = None
    r"""Imported tax amount."""

    tax_rate_imported: Optional[TransactionUpdateTaxRateImported] = None
    r"""Imported tax rate."""

    total_tax_amount_calculated: Optional[TransactionUpdateTotalTaxAmountCalculated] = (
        None
    )
    r"""Calculated tax amount."""

    tax_rate_calculated: Optional[TransactionUpdateTaxRateCalculated] = None
    r"""Calculated tax rate."""

    total_tax_liability_amount: Optional[TransactionUpdateTotalTaxLiabilityAmount] = (
        None
    )
    r"""Total tax liability amount."""

    tax_liability_source: OptionalNullable[TaxLiabilitySourceEnum] = UNSET
    r"""Source of tax liability."""

    taxable_amount: Optional[TransactionUpdateTaxableAmount] = None
    r"""Taxable amount."""

    currency: Optional[CurrencyEnum] = None
    r"""ISO-4217 currency code. Pair with a monetary amount on the same object."""

    locked: Optional[bool] = False
    r"""Transaction lock status."""

    source: Optional[SourceEnum] = None

    connection_id: OptionalNullable[str] = UNSET
    r"""Connection Identifier"""

    filing_id: OptionalNullable[str] = UNSET
    r"""Filing identifier."""

    city: OptionalNullable[str] = UNSET
    r"""City of the transaction address."""

    county: OptionalNullable[str] = UNSET
    r"""County of the transaction address."""

    state: OptionalNullable[str] = UNSET
    r"""State of the transaction address."""

    country: OptionalNullable[CountryCodeEnum] = UNSET
    r"""Country code (ISO Alpha-2)."""

    postal_code: OptionalNullable[str] = UNSET
    r"""Postal code of the transaction."""

    tax_id: Annotated[
        OptionalNullable[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = UNSET
    r"""Tax ID associated with the transaction. DEPRECATED: This field is only populated for QuickBooks integrations and will be removed in a future version."""

    status: Optional[TransactionStatusEnum] = None

    document_type: OptionalNullable[DocumentTypeEnum] = UNSET
    r"""Document type distinguishing invoices from sales orders."""

    created_from: OptionalNullable[str] = UNSET
    r"""Identifier of the invoice that created from a sales order."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "requires_exemption",
                "shop_date",
                "shop_date_tz",
                "description",
                "refund_status",
                "total_amount",
                "customer_id",
                "marketplace",
                "exempt",
                "exemptions",
                "related_to",
                "secondary_external_id",
                "secondary_source",
                "external_friendly_id",
                "total_tax_amount_imported",
                "tax_rate_imported",
                "total_tax_amount_calculated",
                "tax_rate_calculated",
                "total_tax_liability_amount",
                "tax_liability_source",
                "taxable_amount",
                "currency",
                "locked",
                "source",
                "connection_id",
                "filing_id",
                "city",
                "county",
                "state",
                "country",
                "postal_code",
                "tax_id",
                "status",
                "document_type",
                "created_from",
            ]
        )
        nullable_fields = set(
            [
                "requires_exemption",
                "shop_date",
                "shop_date_tz",
                "description",
                "refund_status",
                "customer_id",
                "marketplace",
                "exempt",
                "exemptions",
                "related_to",
                "secondary_external_id",
                "secondary_source",
                "external_friendly_id",
                "tax_liability_source",
                "connection_id",
                "filing_id",
                "city",
                "county",
                "state",
                "country",
                "postal_code",
                "tax_id",
                "document_type",
                "created_from",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TransactionUpdate.model_rebuild()
except NameError:
    pass
