"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sourceenum import SourceEnum
from datetime import datetime
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


QuantityOfTheProductTypedDict = TypeAliasType(
    "QuantityOfTheProductTypedDict", Union[float, str]
)
r"""Defaults to 1.0. The quantity of the item."""


QuantityOfTheProduct = TypeAliasType("QuantityOfTheProduct", Union[float, str])
r"""Defaults to 1.0. The quantity of the item."""


TotalAmountOfThisTransactionItemAfterDiscountsTypedDict = TypeAliasType(
    "TotalAmountOfThisTransactionItemAfterDiscountsTypedDict", Union[float, str]
)
r"""The total amount of the item."""


TotalAmountOfThisTransactionItemAfterDiscounts = TypeAliasType(
    "TotalAmountOfThisTransactionItemAfterDiscounts", Union[float, str]
)
r"""The total amount of the item."""


class TransactionItemEstimateBaseTypedDict(TypedDict):
    date_: datetime
    r"""The date of the transaction item."""
    amount: TotalAmountOfThisTransactionItemAfterDiscountsTypedDict
    r"""The total amount of the item."""
    external_id: NotRequired[Nullable[str]]
    r"""A unique identifier for the transaction item."""
    description: NotRequired[Nullable[str]]
    r"""A description of the item."""
    external_product_id: NotRequired[Nullable[str]]
    r"""External product identifier. If not found and product_subcategory
    and product_category are not provided, an error occurs.
    """
    product_name: NotRequired[Nullable[str]]
    r"""Name of the product. Used if creating a new product."""
    product_description: NotRequired[Nullable[str]]
    r"""Description of the product. Used if creating a new product."""
    product_source: NotRequired[Nullable[SourceEnum]]
    product_subcategory: NotRequired[Nullable[str]]
    r"""Subcategory of the product. Required if product_category is used
    in place of external_product_id.
    """
    product_category: NotRequired[Nullable[str]]
    r"""Category of the product. Required if product_subcategory is used
    in place of external_product_id.
    """
    quantity: NotRequired[QuantityOfTheProductTypedDict]
    r"""Defaults to 1.0. The quantity of the item."""
    exempt: NotRequired[bool]
    r"""Defaults to false. Indicates whether the item is exempt from tax."""
    is_tax_inclusive: NotRequired[bool]
    r"""**Beta — not yet available in production.** When it is not enabled for your environment the field is accepted but ignored, and the response echoes `false`.

    Defaults to false. When true, `amount` is the gross (tax-included) price and the tax is backed out of it rather than added on top; for a taxable line, `taxable_amount` in the response is then the net base.

    When the line is not taxed - exempt, or no tax rule applies in the destination - `taxable_amount` is `0.00` rather than the net base, matching how exempt tax-exclusive lines already behave. Read the net amount as `taxable_amount` when `tax_amount` is non-zero, and as `amount` otherwise.

    This applies to the estimate in this request only. Transactions imported through a connection carry no such flag, so an order quoted here as gross is treated as net when it later syncs, and its recorded tax will be higher than this estimate. Send net amounts on the connection side, or reconcile the difference, until tax-inclusive import support ships.
    """


class TransactionItemEstimateBase(BaseModel):
    date_: Annotated[datetime, pydantic.Field(alias="date")]
    r"""The date of the transaction item."""

    amount: TotalAmountOfThisTransactionItemAfterDiscounts
    r"""The total amount of the item."""

    external_id: OptionalNullable[str] = UNSET
    r"""A unique identifier for the transaction item."""

    description: OptionalNullable[str] = UNSET
    r"""A description of the item."""

    external_product_id: OptionalNullable[str] = UNSET
    r"""External product identifier. If not found and product_subcategory
    and product_category are not provided, an error occurs.
    """

    product_name: OptionalNullable[str] = UNSET
    r"""Name of the product. Used if creating a new product."""

    product_description: OptionalNullable[str] = UNSET
    r"""Description of the product. Used if creating a new product."""

    product_source: OptionalNullable[SourceEnum] = UNSET

    product_subcategory: OptionalNullable[str] = UNSET
    r"""Subcategory of the product. Required if product_category is used
    in place of external_product_id.
    """

    product_category: OptionalNullable[str] = UNSET
    r"""Category of the product. Required if product_subcategory is used
    in place of external_product_id.
    """

    quantity: Optional[QuantityOfTheProduct] = None
    r"""Defaults to 1.0. The quantity of the item."""

    exempt: Optional[bool] = False
    r"""Defaults to false. Indicates whether the item is exempt from tax."""

    is_tax_inclusive: Optional[bool] = False
    r"""**Beta — not yet available in production.** When it is not enabled for your environment the field is accepted but ignored, and the response echoes `false`.

    Defaults to false. When true, `amount` is the gross (tax-included) price and the tax is backed out of it rather than added on top; for a taxable line, `taxable_amount` in the response is then the net base.

    When the line is not taxed - exempt, or no tax rule applies in the destination - `taxable_amount` is `0.00` rather than the net base, matching how exempt tax-exclusive lines already behave. Read the net amount as `taxable_amount` when `tax_amount` is non-zero, and as `amount` otherwise.

    This applies to the estimate in this request only. Transactions imported through a connection carry no such flag, so an order quoted here as gross is treated as net when it later syncs, and its recorded tax will be higher than this estimate. Send net amounts on the connection side, or reconcile the difference, until tax-inclusive import support ships.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "external_id",
                "description",
                "external_product_id",
                "product_name",
                "product_description",
                "product_source",
                "product_subcategory",
                "product_category",
                "quantity",
                "exempt",
                "is_tax_inclusive",
            ]
        )
        nullable_fields = set(
            [
                "external_id",
                "description",
                "external_product_id",
                "product_name",
                "product_description",
                "product_source",
                "product_subcategory",
                "product_category",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    TransactionItemEstimateBase.model_rebuild()
except NameError:
    pass
