"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_upload_registration_attachment_v1_registrations_registration_id_attachments_post import (
    BodyUploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPost,
    BodyUploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPostTypedDict,
)
from kintsugi_tax_platform_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class UploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPostRequestTypedDict(
    TypedDict
):
    registration_id: str
    x_organization_id: Nullable[str]
    r"""The unique identifier for the organization making the request"""
    body_upload_registration_attachment_v1_registrations_registration_id_attachments_post: BodyUploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPostTypedDict


class UploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPostRequest(
    BaseModel
):
    registration_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    x_organization_id: Annotated[
        Nullable[str],
        pydantic.Field(alias="x-organization-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier for the organization making the request"""

    body_upload_registration_attachment_v1_registrations_registration_id_attachments_post: Annotated[
        BodyUploadRegistrationAttachmentV1RegistrationsRegistrationIDAttachmentsPost,
        FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
    ]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
