"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .body_upload_exemption_certificate_v1_exemptions_exemption_id_attachments_post import (
    BodyUploadExemptionCertificateV1ExemptionsExemptionIDAttachmentsPost,
    BodyUploadExemptionCertificateV1ExemptionsExemptionIDAttachmentsPostTypedDict,
)
from kintsugi_tax_platform_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from kintsugi_tax_platform_sdk.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
)
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, TypedDict


class UploadExemptionCertificateV1ExemptionsExemptionIDAttachmentsPostRequestTypedDict(
    TypedDict
):
    exemption_id: str
    r"""The unique identifier for the exemption to which the attachment will be associated."""
    x_organization_id: Nullable[str]
    r"""The unique identifier for the organization making the request"""
    body_upload_exemption_certificate_v1_exemptions_exemption_id_attachments_post: (
        BodyUploadExemptionCertificateV1ExemptionsExemptionIDAttachmentsPostTypedDict
    )


class UploadExemptionCertificateV1ExemptionsExemptionIDAttachmentsPostRequest(
    BaseModel
):
    exemption_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The unique identifier for the exemption to which the attachment will be associated."""

    x_organization_id: Annotated[
        Nullable[str],
        pydantic.Field(alias="x-organization-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""The unique identifier for the organization making the request"""

    body_upload_exemption_certificate_v1_exemptions_exemption_id_attachments_post: (
        Annotated[
            BodyUploadExemptionCertificateV1ExemptionsExemptionIDAttachmentsPost,
            FieldMetadata(request=RequestMetadata(media_type="multipart/form-data")),
        ]
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
