"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .changeregimestatusenum import ChangeRegimeStatusEnum
from .countrycodeenum import CountryCodeEnum
from .filingfrequencyenum import FilingFrequencyEnum
from .registrationsregimeenum import RegistrationsRegimeEnum
from .utahfields import UtahFields, UtahFieldsTypedDict
from datetime import date, datetime
from kintsugi_tax_platform_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from kintsugi_tax_platform_sdk.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


UtahRegistrationPayloadAmountFeesTypedDict = TypeAliasType(
    "UtahRegistrationPayloadAmountFeesTypedDict", Union[float, str]
)
r"""The amount of fees associated with the registration."""


UtahRegistrationPayloadAmountFees = TypeAliasType(
    "UtahRegistrationPayloadAmountFees", Union[float, str]
)
r"""The amount of fees associated with the registration."""


class UtahRegistrationPayloadTypedDict(TypedDict):
    r"""Full payload for Utah registration import."""

    country_code: CountryCodeEnum
    state_code: str
    r"""The state/province code where the registration applies."""
    state_name: str
    r"""The name of the state/province."""
    filing_frequency: FilingFrequencyEnum
    jurisdiction_specific_fields: UtahFieldsTypedDict
    r"""State-specific fields for Utah TAP portal registration import."""
    registration_import_type: Literal["REGULAR"]
    r"""Specifies this is a regular jurisdiction registration import."""
    registration_date: NotRequired[Nullable[date]]
    r"""The date when the registration was created. Format: YYYY-MM-DD."""
    registration_email: NotRequired[Nullable[str]]
    r"""Email address associated with the registration."""
    registration_requested: NotRequired[Nullable[datetime]]
    r"""Timestamp when the registration was requested."""
    registration_completed: NotRequired[Nullable[datetime]]
    r"""Timestamp when the registration was completed."""
    deregistration_requested: NotRequired[Nullable[datetime]]
    r"""Timestamp when deregistration was requested."""
    deregistration_completed: NotRequired[Nullable[datetime]]
    r"""Timestamp when the deregistration was completed."""
    auto_registered: NotRequired[Nullable[bool]]
    r"""Indicates whether the registration was completed automatically."""
    do_not_file: NotRequired[bool]
    r"""If true, do not file for this registration (treated as False by default)."""
    registrations_regime: NotRequired[Nullable[RegistrationsRegimeEnum]]
    r"""The tax registration regime (e.g., STANDARD, SIMPLIFIED)."""
    change_regime_status: NotRequired[Nullable[ChangeRegimeStatusEnum]]
    period_end_month: NotRequired[Nullable[int]]
    r"""Fiscal-year anchor month (1-12) on which each quarterly/semiannual
    period ends, for Hawaii (US-HI) filers whose periods are offset from the calendar.
    Null (default) keeps the standard calendar grid.
    """
    username: NotRequired[Nullable[str]]
    r"""Username for accessing tax registration details."""
    comment: NotRequired[Nullable[str]]
    r"""Additional comments related to the registration."""
    create_filings_from: NotRequired[Nullable[date]]
    r"""The date from which filings should be created. should start (YYYY-MM-DD)."""
    initial_sync: NotRequired[Nullable[bool]]
    r"""Indicates whether an initial synchronization should be performed."""
    amount_fees: NotRequired[UtahRegistrationPayloadAmountFeesTypedDict]
    r"""The amount of fees associated with the registration."""
    vda: NotRequired[Nullable[bool]]
    r"""Indicates whether a Voluntary Disclosure Agreement (VDA) applies."""
    imported: NotRequired[Nullable[bool]]
    r"""Whether the registration was imported from another system."""
    sales_tax_id: NotRequired[Nullable[str]]
    r"""The sales tax ID associated with the registration."""
    ior_number: NotRequired[Nullable[str]]
    r"""The Importer of Record (IOR) number associated with the registration."""
    sst_import: NotRequired[Nullable[bool]]
    r"""Indicates whether the registration is an SST Import."""
    tax_id: NotRequired[Nullable[str]]
    r"""Organization-level tax ID (e.g., VAT number, Canada Business Number)."""
    password_plain_text: NotRequired[Nullable[str]]
    r"""The plaintext password for accessing the tax registration account."""
    password_metadata_plain_text: NotRequired[Nullable[str]]
    r"""Metadata related to the password."""
    pin_plain_text: NotRequired[Nullable[str]]
    r"""6-digit Sales Tax PIN from the Utah sales tax license or mailed separately. Encrypted into pin_encrypted on save."""


class UtahRegistrationPayload(BaseModel):
    r"""Full payload for Utah registration import."""

    country_code: CountryCodeEnum

    state_code: str
    r"""The state/province code where the registration applies."""

    state_name: str
    r"""The name of the state/province."""

    filing_frequency: FilingFrequencyEnum

    jurisdiction_specific_fields: UtahFields
    r"""State-specific fields for Utah TAP portal registration import."""

    REGISTRATION_IMPORT_TYPE: Annotated[
        Annotated[
            Optional[Literal["REGULAR"]], AfterValidator(validate_const("REGULAR"))
        ],
        pydantic.Field(alias="registration_import_type"),
    ] = "REGULAR"
    r"""Specifies this is a regular jurisdiction registration import."""

    registration_date: OptionalNullable[date] = UNSET
    r"""The date when the registration was created. Format: YYYY-MM-DD."""

    registration_email: OptionalNullable[str] = UNSET
    r"""Email address associated with the registration."""

    registration_requested: OptionalNullable[datetime] = UNSET
    r"""Timestamp when the registration was requested."""

    registration_completed: OptionalNullable[datetime] = UNSET
    r"""Timestamp when the registration was completed."""

    deregistration_requested: OptionalNullable[datetime] = UNSET
    r"""Timestamp when deregistration was requested."""

    deregistration_completed: OptionalNullable[datetime] = UNSET
    r"""Timestamp when the deregistration was completed."""

    auto_registered: OptionalNullable[bool] = UNSET
    r"""Indicates whether the registration was completed automatically."""

    do_not_file: Optional[bool] = False
    r"""If true, do not file for this registration (treated as False by default)."""

    registrations_regime: OptionalNullable[RegistrationsRegimeEnum] = UNSET
    r"""The tax registration regime (e.g., STANDARD, SIMPLIFIED)."""

    change_regime_status: OptionalNullable[ChangeRegimeStatusEnum] = UNSET

    period_end_month: OptionalNullable[int] = UNSET
    r"""Fiscal-year anchor month (1-12) on which each quarterly/semiannual
    period ends, for Hawaii (US-HI) filers whose periods are offset from the calendar.
    Null (default) keeps the standard calendar grid.
    """

    username: OptionalNullable[str] = UNSET
    r"""Username for accessing tax registration details."""

    comment: OptionalNullable[str] = UNSET
    r"""Additional comments related to the registration."""

    create_filings_from: OptionalNullable[date] = UNSET
    r"""The date from which filings should be created. should start (YYYY-MM-DD)."""

    initial_sync: OptionalNullable[bool] = UNSET
    r"""Indicates whether an initial synchronization should be performed."""

    amount_fees: Optional[UtahRegistrationPayloadAmountFees] = None
    r"""The amount of fees associated with the registration."""

    vda: OptionalNullable[bool] = UNSET
    r"""Indicates whether a Voluntary Disclosure Agreement (VDA) applies."""

    imported: OptionalNullable[bool] = UNSET
    r"""Whether the registration was imported from another system."""

    sales_tax_id: OptionalNullable[str] = UNSET
    r"""The sales tax ID associated with the registration."""

    ior_number: OptionalNullable[str] = UNSET
    r"""The Importer of Record (IOR) number associated with the registration."""

    sst_import: OptionalNullable[bool] = UNSET
    r"""Indicates whether the registration is an SST Import."""

    tax_id: OptionalNullable[str] = UNSET
    r"""Organization-level tax ID (e.g., VAT number, Canada Business Number)."""

    password_plain_text: OptionalNullable[str] = UNSET
    r"""The plaintext password for accessing the tax registration account."""

    password_metadata_plain_text: OptionalNullable[str] = UNSET
    r"""Metadata related to the password."""

    pin_plain_text: OptionalNullable[str] = UNSET
    r"""6-digit Sales Tax PIN from the Utah sales tax license or mailed separately. Encrypted into pin_encrypted on save."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "registration_import_type",
                "registration_date",
                "registration_email",
                "registration_requested",
                "registration_completed",
                "deregistration_requested",
                "deregistration_completed",
                "auto_registered",
                "do_not_file",
                "registrations_regime",
                "change_regime_status",
                "period_end_month",
                "username",
                "comment",
                "create_filings_from",
                "initial_sync",
                "amount_fees",
                "vda",
                "imported",
                "sales_tax_id",
                "ior_number",
                "sst_import",
                "tax_id",
                "password_plain_text",
                "password_metadata_plain_text",
                "pin_plain_text",
            ]
        )
        nullable_fields = set(
            [
                "registration_date",
                "registration_email",
                "registration_requested",
                "registration_completed",
                "deregistration_requested",
                "deregistration_completed",
                "auto_registered",
                "registrations_regime",
                "change_regime_status",
                "period_end_month",
                "username",
                "comment",
                "create_filings_from",
                "initial_sync",
                "vda",
                "imported",
                "sales_tax_id",
                "ior_number",
                "sst_import",
                "tax_id",
                "password_plain_text",
                "password_metadata_plain_text",
                "pin_plain_text",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UtahRegistrationPayload.model_rebuild()
except NameError:
    pass
