"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class UtahRegistrationType(str, Enum):
    SALES_TAX = "SALES_TAX"
    USE_TAX = "USE_TAX"
