"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class VirginiaRegistrationType(str, Enum):
    RETAIL_SALES_TAX = "RETAIL_SALES_TAX"
    USE_TAX = "USE_TAX"
