"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .westvirginiaregistrationtype import WestVirginiaRegistrationType
from kintsugi_tax_platform_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class WestVirginiaFieldsTypedDict(TypedDict):
    r"""State-specific fields for West Virginia MyTaxes portal registration import."""

    registration_type: WestVirginiaRegistrationType
    business_name: str
    r"""State-registered business name as shown in West Virginia MyTaxes."""
    wv_state_tax_id: str
    r"""West Virginia state-issued tax identification number (WV State Tax ID)."""
    mfa_completed: NotRequired[bool]
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their West Virginia MyTaxes account."""
    third_party_access_enabled: NotRequired[bool]
    r"""Whether third-party access has been granted to Kintsugi in MyTaxes."""


class WestVirginiaFields(BaseModel):
    r"""State-specific fields for West Virginia MyTaxes portal registration import."""

    registration_type: WestVirginiaRegistrationType

    business_name: str
    r"""State-registered business name as shown in West Virginia MyTaxes."""

    wv_state_tax_id: str
    r"""West Virginia state-issued tax identification number (WV State Tax ID)."""

    mfa_completed: Optional[bool] = False
    r"""Whether the customer has completed MFA setup using the Kintsugi virtual mail group ID on their West Virginia MyTaxes account."""

    third_party_access_enabled: Optional[bool] = False
    r"""Whether third-party access has been granted to Kintsugi in MyTaxes."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["mfa_completed", "third_party_access_enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
