"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from kintsugi_tax_platform_sdk.types import BaseModel
from kintsugi_tax_platform_sdk.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict


class WyomingFieldsTypedDict(TypedDict):
    r"""State-specific fields for Wyoming (WYPath) registration import.

    Wyoming (WYIFS / WYPath) does not use or require 2FA/MFA, so there is no
    ``mfa_completed`` field. There is also no dedicated third-party master account
    for sales and use tax, so there is no ``third_party_access_enabled`` field.
    The State PIN is collected via the optional top-level ``pin_plain_text`` field
    (encrypted into ``pin_encrypted``), not JSF — same pattern as Arizona.
    """

    business_name: str
    r"""State-registered business name as shown in Wyoming WYPath."""
    wy_state_tax_id: str
    r"""Wyoming state-issued tax ID (Wyoming State Tax ID)."""
    registration_type: Literal["SALES_AND_USE_TAX"]
    r"""Registration type for this Wyoming import: sales and use tax."""


class WyomingFields(BaseModel):
    r"""State-specific fields for Wyoming (WYPath) registration import.

    Wyoming (WYIFS / WYPath) does not use or require 2FA/MFA, so there is no
    ``mfa_completed`` field. There is also no dedicated third-party master account
    for sales and use tax, so there is no ``third_party_access_enabled`` field.
    The State PIN is collected via the optional top-level ``pin_plain_text`` field
    (encrypted into ``pin_encrypted``), not JSF — same pattern as Arizona.
    """

    business_name: str
    r"""State-registered business name as shown in Wyoming WYPath."""

    wy_state_tax_id: str
    r"""Wyoming state-issued tax ID (Wyoming State Tax ID)."""

    REGISTRATION_TYPE: Annotated[
        Annotated[
            Literal["SALES_AND_USE_TAX"],
            AfterValidator(validate_const("SALES_AND_USE_TAX")),
        ],
        pydantic.Field(alias="registration_type"),
    ] = "SALES_AND_USE_TAX"
    r"""Registration type for this Wyoming import: sales and use tax."""


try:
    WyomingFields.model_rebuild()
except NameError:
    pass
