"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from datetime import date
from kintsugi_tax_platform_sdk import errors, models, utils
from kintsugi_tax_platform_sdk._hooks import HookContext
from kintsugi_tax_platform_sdk.types import Nullable, OptionalNullable, UNSET
from kintsugi_tax_platform_sdk.utils.unmarshal_json_response import (
    unmarshal_json_response,
)
from typing import Any, List, Mapping, Optional


class Nexus(BaseSDK):
    def get_all(
        self,
        *,
        x_organization_id: Nullable[str],
        without_pagination: Optional[bool] = False,
        disregard_view: OptionalNullable[str] = UNSET,
        search_query: OptionalNullable[str] = UNSET,
        status_in: OptionalNullable[str] = UNSET,
        state_code: OptionalNullable[str] = UNSET,
        state_code_in: OptionalNullable[str] = UNSET,
        country_code_in: OptionalNullable[str] = UNSET,
        tax_type_in: OptionalNullable[str] = UNSET,
        order_by: OptionalNullable[str] = UNSET,
        collected_tax_nexus_met: OptionalNullable[bool] = UNSET,
        page: Optional[int] = 1,
        size: Optional[int] = 50,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ResponseGetNexusForOrgV1NexusGet:
        r"""Get nexus for org

        Get a list of all nexuses for the organization.

        :param x_organization_id: The unique identifier for the organization making the request
        :param without_pagination: Return all results without pagination
        :param disregard_view: Filter nexuses by disregard view: 'exposed' or 'disregarded'
        :param search_query: Search nexuses by state code or state name
        :param status_in:
        :param state_code:
        :param state_code_in:
        :param country_code_in:
        :param tax_type_in:
        :param order_by:
        :param collected_tax_nexus_met:
        :param page:
        :param size:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetNexusForOrgV1NexusGetRequest(
            without_pagination=without_pagination,
            disregard_view=disregard_view,
            search_query=search_query,
            status_in=status_in,
            state_code=state_code,
            state_code_in=state_code_in,
            country_code_in=country_code_in,
            tax_type_in=tax_type_in,
            order_by=order_by,
            collected_tax_nexus_met=collected_tax_nexus_met,
            page=page,
            size=size,
            x_organization_id=x_organization_id,
        )

        req = self._build_request(
            method="GET",
            path="/v1/nexus",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_nexus_for_org_v1_nexus_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.ResponseGetNexusForOrgV1NexusGet, http_res
            )
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def get_all_async(
        self,
        *,
        x_organization_id: Nullable[str],
        without_pagination: Optional[bool] = False,
        disregard_view: OptionalNullable[str] = UNSET,
        search_query: OptionalNullable[str] = UNSET,
        status_in: OptionalNullable[str] = UNSET,
        state_code: OptionalNullable[str] = UNSET,
        state_code_in: OptionalNullable[str] = UNSET,
        country_code_in: OptionalNullable[str] = UNSET,
        tax_type_in: OptionalNullable[str] = UNSET,
        order_by: OptionalNullable[str] = UNSET,
        collected_tax_nexus_met: OptionalNullable[bool] = UNSET,
        page: Optional[int] = 1,
        size: Optional[int] = 50,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ResponseGetNexusForOrgV1NexusGet:
        r"""Get nexus for org

        Get a list of all nexuses for the organization.

        :param x_organization_id: The unique identifier for the organization making the request
        :param without_pagination: Return all results without pagination
        :param disregard_view: Filter nexuses by disregard view: 'exposed' or 'disregarded'
        :param search_query: Search nexuses by state code or state name
        :param status_in:
        :param state_code:
        :param state_code_in:
        :param country_code_in:
        :param tax_type_in:
        :param order_by:
        :param collected_tax_nexus_met:
        :param page:
        :param size:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetNexusForOrgV1NexusGetRequest(
            without_pagination=without_pagination,
            disregard_view=disregard_view,
            search_query=search_query,
            status_in=status_in,
            state_code=state_code,
            state_code_in=state_code_in,
            country_code_in=country_code_in,
            tax_type_in=tax_type_in,
            order_by=order_by,
            collected_tax_nexus_met=collected_tax_nexus_met,
            page=page,
            size=size,
            x_organization_id=x_organization_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/nexus",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_nexus_for_org_v1_nexus_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.ResponseGetNexusForOrgV1NexusGet, http_res
            )
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def get_physical(
        self,
        *,
        x_organization_id: Nullable[str],
        country_code: OptionalNullable[str] = UNSET,
        state_code: OptionalNullable[str] = UNSET,
        order_by: OptionalNullable[str] = UNSET,
        page: Optional[int] = 1,
        size: Optional[int] = 50,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PagePhysicalNexusRead:
        r"""Get physical nexus

        Retrieve a paginated list of
        physical nexuses for a specific organization.

        :param x_organization_id: The unique identifier for the organization making the request
        :param country_code:
        :param state_code:
        :param order_by:
        :param page: Page number
        :param size: Page size
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPhysicalNexusV1NexusPhysicalNexusGetRequest(
            country_code=country_code,
            state_code=state_code,
            order_by=order_by,
            page=page,
            size=size,
            x_organization_id=x_organization_id,
        )

        req = self._build_request(
            method="GET",
            path="/v1/nexus/physical_nexus",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_physical_nexus_v1_nexus_physical_nexus_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PagePhysicalNexusRead, http_res)
        if utils.match_response(http_res, ["401", "404"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def get_physical_async(
        self,
        *,
        x_organization_id: Nullable[str],
        country_code: OptionalNullable[str] = UNSET,
        state_code: OptionalNullable[str] = UNSET,
        order_by: OptionalNullable[str] = UNSET,
        page: Optional[int] = 1,
        size: Optional[int] = 50,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PagePhysicalNexusRead:
        r"""Get physical nexus

        Retrieve a paginated list of
        physical nexuses for a specific organization.

        :param x_organization_id: The unique identifier for the organization making the request
        :param country_code:
        :param state_code:
        :param order_by:
        :param page: Page number
        :param size: Page size
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetPhysicalNexusV1NexusPhysicalNexusGetRequest(
            country_code=country_code,
            state_code=state_code,
            order_by=order_by,
            page=page,
            size=size,
            x_organization_id=x_organization_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/nexus/physical_nexus",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_physical_nexus_v1_nexus_physical_nexus_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PagePhysicalNexusRead, http_res)
        if utils.match_response(http_res, ["401", "404"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def create_physical(
        self,
        *,
        x_organization_id: Nullable[str],
        country_code: models.CountryCodeEnum,
        state_code: str,
        start_date: date,
        category: models.PhysicalNexusCategory,
        end_date: OptionalNullable[date] = UNSET,
        external_id: OptionalNullable[str] = UNSET,
        source: Optional[models.PhysicalNexusSource] = None,
        street_1: OptionalNullable[str] = UNSET,
        street_2: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        postal_code: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PhysicalNexusRead:
        r"""Create physical nexus

        The Create Physical Nexus API allows you to create a new physical
        nexus by specifying its attributes, including the location,
        start date, end date, etc.

        :param x_organization_id: The unique identifier for the organization making the request
        :param country_code:
        :param state_code: The state or province code in
            ISO 3166-2 format (e.g., CA).
        :param start_date: The date when the nexus became
            effective (YYYY-MM-DD).
        :param category:
        :param end_date: The date when the
            nexus ended, if applicable.
        :param external_id: Optional
            external identifier for the nexus.
        :param source:
        :param street_1: Primary street address for the physical presence location.
        :param street_2: Additional street address details, such as suite or unit number.
        :param city: City of the physical presence location.
        :param postal_code: ZIP or postal code of the physical presence location.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreatePhysicalNexusV1NexusPhysicalNexusPostRequest(
            x_organization_id=x_organization_id,
            physical_nexus_create=models.PhysicalNexusCreate(
                country_code=country_code,
                state_code=state_code,
                start_date=start_date,
                end_date=end_date,
                category=category,
                external_id=external_id,
                source=source,
                street_1=street_1,
                street_2=street_2,
                city=city,
                postal_code=postal_code,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/v1/nexus/physical_nexus",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.physical_nexus_create,
                False,
                False,
                "json",
                models.PhysicalNexusCreate,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create_physical_nexus_v1_nexus_physical_nexus_post",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PhysicalNexusRead, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def create_physical_async(
        self,
        *,
        x_organization_id: Nullable[str],
        country_code: models.CountryCodeEnum,
        state_code: str,
        start_date: date,
        category: models.PhysicalNexusCategory,
        end_date: OptionalNullable[date] = UNSET,
        external_id: OptionalNullable[str] = UNSET,
        source: Optional[models.PhysicalNexusSource] = None,
        street_1: OptionalNullable[str] = UNSET,
        street_2: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        postal_code: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PhysicalNexusRead:
        r"""Create physical nexus

        The Create Physical Nexus API allows you to create a new physical
        nexus by specifying its attributes, including the location,
        start date, end date, etc.

        :param x_organization_id: The unique identifier for the organization making the request
        :param country_code:
        :param state_code: The state or province code in
            ISO 3166-2 format (e.g., CA).
        :param start_date: The date when the nexus became
            effective (YYYY-MM-DD).
        :param category:
        :param end_date: The date when the
            nexus ended, if applicable.
        :param external_id: Optional
            external identifier for the nexus.
        :param source:
        :param street_1: Primary street address for the physical presence location.
        :param street_2: Additional street address details, such as suite or unit number.
        :param city: City of the physical presence location.
        :param postal_code: ZIP or postal code of the physical presence location.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.CreatePhysicalNexusV1NexusPhysicalNexusPostRequest(
            x_organization_id=x_organization_id,
            physical_nexus_create=models.PhysicalNexusCreate(
                country_code=country_code,
                state_code=state_code,
                start_date=start_date,
                end_date=end_date,
                category=category,
                external_id=external_id,
                source=source,
                street_1=street_1,
                street_2=street_2,
                city=city,
                postal_code=postal_code,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/v1/nexus/physical_nexus",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.physical_nexus_create,
                False,
                False,
                "json",
                models.PhysicalNexusCreate,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="create_physical_nexus_v1_nexus_physical_nexus_post",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PhysicalNexusRead, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def get_physical_nexus_categories_v1_nexus_physical_nexus_categories_get(
        self,
        *,
        x_organization_id: Nullable[str],
        country_code: OptionalNullable[models.CountryCodeEnum] = UNSET,
        state_code: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.PhysicalNexusCategories]:
        r"""Get physical nexus categories

        Get physical nexus categories

        :param x_organization_id: The unique identifier for the organization making the request
        :param country_code:
        :param state_code:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.GetPhysicalNexusCategoriesV1NexusPhysicalNexusCategoriesGetRequest(
                country_code=country_code,
                state_code=state_code,
                x_organization_id=x_organization_id,
            )
        )

        req = self._build_request(
            method="GET",
            path="/v1/nexus/physical_nexus/categories",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_physical_nexus_categories_v1_nexus_physical_nexus_categories_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                List[models.PhysicalNexusCategories], http_res
            )
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def get_physical_nexus_categories_v1_nexus_physical_nexus_categories_get_async(
        self,
        *,
        x_organization_id: Nullable[str],
        country_code: OptionalNullable[models.CountryCodeEnum] = UNSET,
        state_code: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.PhysicalNexusCategories]:
        r"""Get physical nexus categories

        Get physical nexus categories

        :param x_organization_id: The unique identifier for the organization making the request
        :param country_code:
        :param state_code:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.GetPhysicalNexusCategoriesV1NexusPhysicalNexusCategoriesGetRequest(
                country_code=country_code,
                state_code=state_code,
                x_organization_id=x_organization_id,
            )
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/nexus/physical_nexus/categories",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_physical_nexus_categories_v1_nexus_physical_nexus_categories_get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                List[models.PhysicalNexusCategories], http_res
            )
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def delete_physical_nexus(
        self,
        *,
        physical_nexus_id: str,
        x_organization_id: Nullable[str],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Delete physical nexus

        The Delete Physical Nexus API allows you to remove an existing
        physical nexus by its unique ID.

        :param physical_nexus_id: The unique identifier of the physical
            nexus to delete.
        :param x_organization_id: The unique identifier for the organization making the request
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.DeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIDDeleteRequest(
                physical_nexus_id=physical_nexus_id,
                x_organization_id=x_organization_id,
            )
        )

        req = self._build_request(
            method="DELETE",
            path="/v1/nexus/physical_nexus/{physical_nexus_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete_physical_nexus_v1_nexus_physical_nexus__physical_nexus_id__delete",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, ["401", "404"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def delete_physical_nexus_async(
        self,
        *,
        physical_nexus_id: str,
        x_organization_id: Nullable[str],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Delete physical nexus

        The Delete Physical Nexus API allows you to remove an existing
        physical nexus by its unique ID.

        :param physical_nexus_id: The unique identifier of the physical
            nexus to delete.
        :param x_organization_id: The unique identifier for the organization making the request
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.DeletePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIDDeleteRequest(
                physical_nexus_id=physical_nexus_id,
                x_organization_id=x_organization_id,
            )
        )

        req = self._build_request_async(
            method="DELETE",
            path="/v1/nexus/physical_nexus/{physical_nexus_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="delete_physical_nexus_v1_nexus_physical_nexus__physical_nexus_id__delete",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(Any, http_res)
        if utils.match_response(http_res, ["401", "404"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def update_physical_nexus(
        self,
        *,
        physical_nexus_id: str,
        x_organization_id: Nullable[str],
        start_date: date,
        category: models.PhysicalNexusCategory,
        end_date: OptionalNullable[date] = UNSET,
        street_1: OptionalNullable[str] = UNSET,
        street_2: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        postal_code: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PhysicalNexusRead:
        r"""Update physical nexus

        The Update Physical Nexus API allows you to modify the details of
        an existing physical nexus by its unique ID.

        :param physical_nexus_id: The unique identifier of the physical
            nexus to update.
        :param x_organization_id: The unique identifier for the organization making the request
        :param start_date: The date when the nexus became
            effective (YYYY-MM-DD).
        :param category:
        :param end_date: The date when the
            nexus ends, if applicable (YYYY-MM-DD).
        :param street_1: Primary street address for the physical presence location.
        :param street_2: Additional street address details, such as suite or unit number.
        :param city: City of the physical presence location.
        :param postal_code: ZIP or postal code of the physical presence location.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIDPutRequest(
                physical_nexus_id=physical_nexus_id,
                x_organization_id=x_organization_id,
                physical_nexus_update=models.PhysicalNexusUpdate(
                    start_date=start_date,
                    end_date=end_date,
                    category=category,
                    street_1=street_1,
                    street_2=street_2,
                    city=city,
                    postal_code=postal_code,
                ),
            )
        )

        req = self._build_request(
            method="PUT",
            path="/v1/nexus/physical_nexus/{physical_nexus_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.physical_nexus_update,
                False,
                False,
                "json",
                models.PhysicalNexusUpdate,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update_physical_nexus_v1_nexus_physical_nexus__physical_nexus_id__put",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PhysicalNexusRead, http_res)
        if utils.match_response(http_res, ["401", "404"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def update_physical_nexus_async(
        self,
        *,
        physical_nexus_id: str,
        x_organization_id: Nullable[str],
        start_date: date,
        category: models.PhysicalNexusCategory,
        end_date: OptionalNullable[date] = UNSET,
        street_1: OptionalNullable[str] = UNSET,
        street_2: OptionalNullable[str] = UNSET,
        city: OptionalNullable[str] = UNSET,
        postal_code: OptionalNullable[str] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PhysicalNexusRead:
        r"""Update physical nexus

        The Update Physical Nexus API allows you to modify the details of
        an existing physical nexus by its unique ID.

        :param physical_nexus_id: The unique identifier of the physical
            nexus to update.
        :param x_organization_id: The unique identifier for the organization making the request
        :param start_date: The date when the nexus became
            effective (YYYY-MM-DD).
        :param category:
        :param end_date: The date when the
            nexus ends, if applicable (YYYY-MM-DD).
        :param street_1: Primary street address for the physical presence location.
        :param street_2: Additional street address details, such as suite or unit number.
        :param city: City of the physical presence location.
        :param postal_code: ZIP or postal code of the physical presence location.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = (
            models.UpdatePhysicalNexusV1NexusPhysicalNexusPhysicalNexusIDPutRequest(
                physical_nexus_id=physical_nexus_id,
                x_organization_id=x_organization_id,
                physical_nexus_update=models.PhysicalNexusUpdate(
                    start_date=start_date,
                    end_date=end_date,
                    category=category,
                    street_1=street_1,
                    street_2=street_2,
                    city=city,
                    postal_code=postal_code,
                ),
            )
        )

        req = self._build_request_async(
            method="PUT",
            path="/v1/nexus/physical_nexus/{physical_nexus_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.physical_nexus_update,
                False,
                False,
                "json",
                models.PhysicalNexusUpdate,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="update_physical_nexus_v1_nexus_physical_nexus__physical_nexus_id__put",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.PhysicalNexusRead, http_res)
        if utils.match_response(http_res, ["401", "404"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.BackendSrcNexusResponsesValidationErrorResponseData, http_res
            )
            raise errors.BackendSrcNexusResponsesValidationErrorResponse(
                response_data, http_res
            )
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(errors.ErrorResponseData, http_res)
            raise errors.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def get_nexus_details_for_id_v1_nexus_nexus_id_get(
        self,
        *,
        nexus_id: str,
        x_organization_id: Nullable[str],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.NexusResponse:
        r"""Get nexus details for id

        Get details for a specific nexus by its ID.

        :param nexus_id: The unique identifier of the nexus.
        :param x_organization_id: The unique identifier for the organization making the request
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetNexusDetailsForIDV1NexusNexusIDGetRequest(
            nexus_id=nexus_id,
            x_organization_id=x_organization_id,
        )

        req = self._build_request(
            method="GET",
            path="/v1/nexus/{nexus_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_nexus_details_for_id_v1_nexus__nexus_id__get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.NexusResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def get_nexus_details_for_id_v1_nexus_nexus_id_get_async(
        self,
        *,
        nexus_id: str,
        x_organization_id: Nullable[str],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.NexusResponse:
        r"""Get nexus details for id

        Get details for a specific nexus by its ID.

        :param nexus_id: The unique identifier of the nexus.
        :param x_organization_id: The unique identifier for the organization making the request
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetNexusDetailsForIDV1NexusNexusIDGetRequest(
            nexus_id=nexus_id,
            x_organization_id=x_organization_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/nexus/{nexus_id}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="get_nexus_details_for_id_v1_nexus__nexus_id__get",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Nexus"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.NexusResponse, http_res)
        if utils.match_response(http_res, "422", "application/json"):
            response_data = unmarshal_json_response(
                errors.HTTPValidationErrorData, http_res
            )
            raise errors.HTTPValidationError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)
