workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    kintsugi-overlay:
        inputs:
            - location: https://api.trykintsugi.com/openapi.json
        overlays:
            - location: ./overlay.yaml
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: output.yaml
        registry:
            location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay
targets:
    python:
        target: python
        source: kintsugi-overlay
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/kintsugi-ai/tax-platform/kintsugi-overlay-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false 